theory Privations_S5_Skeleton
  imports Main
begin

typedecl i  (* individuals *)
consts g :: i  c :: i

consts Saved :: "i ⇒ bool"
consts Reconciled :: "i ⇒ bool"
consts Pi :: "i ⇒ bool"   (* corrective active *)

consts Priv_I_UNIVERSAL_PRIVATION_FOUNDATION :: "i ⇒ bool"
consts Positive_I_UNIVERSAL_PRIVATION_FOUNDATION :: "i ⇒ bool"
consts Restore_I_UNIVERSAL_PRIVATION_FOUNDATION :: "i ⇒ bool"
consts mu_I_UNIVERSAL_PRIVATION_FOUNDATION :: "i ⇒ real"
axiomatization where mu_I_UNIVERSAL_PRIVATION_FOUNDATION_nonneg: "∀x. 0 ≤ mu_I_UNIVERSAL_PRIVATION_FOUNDATION x"
  and restore_I_UNIVERSAL_PRIVATION_FOUNDATION_iff_mu_zero: "∀x. mu_I_UNIVERSAL_PRIVATION_FOUNDATION x = 0 ⟶ Restore_I_UNIVERSAL_PRIVATION_FOUNDATION x"

consts Priv_Universal_Privation_Pattern :: "i ⇒ bool"
consts Positive_Universal_Privation_Pattern :: "i ⇒ bool"
consts Restore_Universal_Privation_Pattern :: "i ⇒ bool"
consts mu_Universal_Privation_Pattern :: "i ⇒ real"
axiomatization where mu_Universal_Privation_Pattern_nonneg: "∀x. 0 ≤ mu_Universal_Privation_Pattern x"
  and restore_Universal_Privation_Pattern_iff_mu_zero: "∀x. mu_Universal_Privation_Pattern x = 0 ⟶ Restore_Universal_Privation_Pattern x"

consts Priv_Complete_Privation_Taxonomy :: "i ⇒ bool"
consts Positive_Complete_Privation_Taxonomy :: "i ⇒ bool"
consts Restore_Complete_Privation_Taxonomy :: "i ⇒ bool"
consts mu_Complete_Privation_Taxonomy :: "i ⇒ real"
axiomatization where mu_Complete_Privation_Taxonomy_nonneg: "∀x. 0 ≤ mu_Complete_Privation_Taxonomy x"
  and restore_Complete_Privation_Taxonomy_iff_mu_zero: "∀x. mu_Complete_Privation_Taxonomy x = 0 ⟶ Restore_Complete_Privation_Taxonomy x"

consts Priv_II_META_PRIVATION_INCOHERENCE :: "i ⇒ bool"
consts Positive_II_META_PRIVATION_INCOHERENCE :: "i ⇒ bool"
consts Restore_II_META_PRIVATION_INCOHERENCE :: "i ⇒ bool"
consts mu_II_META_PRIVATION_INCOHERENCE :: "i ⇒ real"
axiomatization where mu_II_META_PRIVATION_INCOHERENCE_nonneg: "∀x. 0 ≤ mu_II_META_PRIVATION_INCOHERENCE x"
  and restore_II_META_PRIVATION_INCOHERENCE_iff_mu_zero: "∀x. mu_II_META_PRIVATION_INCOHERENCE x = 0 ⟶ Restore_II_META_PRIVATION_INCOHERENCE x"

consts Priv_Incoherence_Privation_Formalism_IPF :: "i ⇒ bool"
consts Positive_Incoherence_Privation_Formalism_IPF :: "i ⇒ bool"
consts Restore_Incoherence_Privation_Formalism_IPF :: "i ⇒ bool"
consts mu_Incoherence_Privation_Formalism_IPF :: "i ⇒ real"
axiomatization where mu_Incoherence_Privation_Formalism_IPF_nonneg: "∀x. 0 ≤ mu_Incoherence_Privation_Formalism_IPF x"
  and restore_Incoherence_Privation_Formalism_IPF_iff_mu_zero: "∀x. mu_Incoherence_Privation_Formalism_IPF x = 0 ⟶ Restore_Incoherence_Privation_Formalism_IPF x"

consts Priv_IPF_1_x_Incoherent_x_E_positive_logic_x :: "i ⇒ bool"
consts Positive_IPF_1_x_Incoherent_x_E_positive_logic_x :: "i ⇒ bool"
consts Restore_IPF_1_x_Incoherent_x_E_positive_logic_x :: "i ⇒ bool"
consts mu_IPF_1_x_Incoherent_x_E_positive_logic_x :: "i ⇒ real"
axiomatization where mu_IPF_1_x_Incoherent_x_E_positive_logic_x_nonneg: "∀x. 0 ≤ mu_IPF_1_x_Incoherent_x_E_positive_logic_x x"
  and restore_IPF_1_x_Incoherent_x_E_positive_logic_x_iff_mu_zero: "∀x. mu_IPF_1_x_Incoherent_x_E_positive_logic_x x = 0 ⟶ Restore_IPF_1_x_Incoherent_x_E_positive_logic_x x"

consts Priv_IPF_2_x_Incoherent_x_y_C_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Positive_IPF_2_x_Incoherent_x_y_C_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Restore_IPF_2_x_Incoherent_x_y_C_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts mu_IPF_2_x_Incoherent_x_y_C_y_Dependent_on_contrast_x_y :: "i ⇒ real"
axiomatization where mu_IPF_2_x_Incoherent_x_y_C_y_Dependent_on_contrast_x_y_nonneg: "∀x. 0 ≤ mu_IPF_2_x_Incoherent_x_y_C_y_Dependent_on_contrast_x_y x"
  and restore_IPF_2_x_Incoherent_x_y_C_y_Dependent_on_contrast_x_y_iff_mu_zero: "∀x. mu_IPF_2_x_Incoherent_x_y_C_y_Dependent_on_contrast_x_y x = 0 ⟶ Restore_IPF_2_x_Incoherent_x_y_C_y_Dependent_on_contrast_x_y x"

consts Priv_IPF_3_x_Incoherent_x_Coherence_Restorable_x :: "i ⇒ bool"
consts Positive_IPF_3_x_Incoherent_x_Coherence_Restorable_x :: "i ⇒ bool"
consts Restore_IPF_3_x_Incoherent_x_Coherence_Restorable_x :: "i ⇒ bool"
consts mu_IPF_3_x_Incoherent_x_Coherence_Restorable_x :: "i ⇒ real"
axiomatization where mu_IPF_3_x_Incoherent_x_Coherence_Restorable_x_nonneg: "∀x. 0 ≤ mu_IPF_3_x_Incoherent_x_Coherence_Restorable_x x"
  and restore_IPF_3_x_Incoherent_x_Coherence_Restorable_x_iff_mu_zero: "∀x. mu_IPF_3_x_Incoherent_x_Coherence_Restorable_x x = 0 ⟶ Restore_IPF_3_x_Incoherent_x_Coherence_Restorable_x x"

consts Priv_IPF_T1_x_Incoherent_x_Logic_Optimizable_x :: "i ⇒ bool"
consts Positive_IPF_T1_x_Incoherent_x_Logic_Optimizable_x :: "i ⇒ bool"
consts Restore_IPF_T1_x_Incoherent_x_Logic_Optimizable_x :: "i ⇒ bool"
consts mu_IPF_T1_x_Incoherent_x_Logic_Optimizable_x :: "i ⇒ real"
axiomatization where mu_IPF_T1_x_Incoherent_x_Logic_Optimizable_x_nonneg: "∀x. 0 ≤ mu_IPF_T1_x_Incoherent_x_Logic_Optimizable_x x"
  and restore_IPF_T1_x_Incoherent_x_Logic_Optimizable_x_iff_mu_zero: "∀x. mu_IPF_T1_x_Incoherent_x_Logic_Optimizable_x x = 0 ⟶ Restore_IPF_T1_x_Incoherent_x_Logic_Optimizable_x x"

consts Priv_IPF_T2_x_Incoherent_x_y_C_y_Restores_Logic_y_x :: "i ⇒ bool"
consts Positive_IPF_T2_x_Incoherent_x_y_C_y_Restores_Logic_y_x :: "i ⇒ bool"
consts Restore_IPF_T2_x_Incoherent_x_y_C_y_Restores_Logic_y_x :: "i ⇒ bool"
consts mu_IPF_T2_x_Incoherent_x_y_C_y_Restores_Logic_y_x :: "i ⇒ real"
axiomatization where mu_IPF_T2_x_Incoherent_x_y_C_y_Restores_Logic_y_x_nonneg: "∀x. 0 ≤ mu_IPF_T2_x_Incoherent_x_y_C_y_Restores_Logic_y_x x"
  and restore_IPF_T2_x_Incoherent_x_y_C_y_Restores_Logic_y_x_iff_mu_zero: "∀x. mu_IPF_T2_x_Incoherent_x_y_C_y_Restores_Logic_y_x x = 0 ⟶ Restore_IPF_T2_x_Incoherent_x_y_C_y_Restores_Logic_y_x x"

consts Priv_IPF_T3_x_Incoherent_x_Creates_Coherence_ex_nihilo_x :: "i ⇒ bool"
consts Positive_IPF_T3_x_Incoherent_x_Creates_Coherence_ex_nihilo_x :: "i ⇒ bool"
consts Restore_IPF_T3_x_Incoherent_x_Creates_Coherence_ex_nihilo_x :: "i ⇒ bool"
consts mu_IPF_T3_x_Incoherent_x_Creates_Coherence_ex_nihilo_x :: "i ⇒ real"
axiomatization where mu_IPF_T3_x_Incoherent_x_Creates_Coherence_ex_nihilo_x_nonneg: "∀x. 0 ≤ mu_IPF_T3_x_Incoherent_x_Creates_Coherence_ex_nihilo_x x"
  and restore_IPF_T3_x_Incoherent_x_Creates_Coherence_ex_nihilo_x_iff_mu_zero: "∀x. mu_IPF_T3_x_Incoherent_x_Creates_Coherence_ex_nihilo_x x = 0 ⟶ Restore_IPF_T3_x_Incoherent_x_Creates_Coherence_ex_nihilo_x x"

consts Priv_III_FUNDAMENTAL_PRIVATIONS :: "i ⇒ bool"
consts Positive_III_FUNDAMENTAL_PRIVATIONS :: "i ⇒ bool"
consts Restore_III_FUNDAMENTAL_PRIVATIONS :: "i ⇒ bool"
consts mu_III_FUNDAMENTAL_PRIVATIONS :: "i ⇒ real"
axiomatization where mu_III_FUNDAMENTAL_PRIVATIONS_nonneg: "∀x. 0 ≤ mu_III_FUNDAMENTAL_PRIVATIONS x"
  and restore_III_FUNDAMENTAL_PRIVATIONS_iff_mu_zero: "∀x. mu_III_FUNDAMENTAL_PRIVATIONS x = 0 ⟶ Restore_III_FUNDAMENTAL_PRIVATIONS x"

consts Priv_1_Evil_Privation_Formalism_EPF :: "i ⇒ bool"
consts Positive_1_Evil_Privation_Formalism_EPF :: "i ⇒ bool"
consts Restore_1_Evil_Privation_Formalism_EPF :: "i ⇒ bool"
consts mu_1_Evil_Privation_Formalism_EPF :: "i ⇒ real"
axiomatization where mu_1_Evil_Privation_Formalism_EPF_nonneg: "∀x. 0 ≤ mu_1_Evil_Privation_Formalism_EPF x"
  and restore_1_Evil_Privation_Formalism_EPF_iff_mu_zero: "∀x. mu_1_Evil_Privation_Formalism_EPF x = 0 ⟶ Restore_1_Evil_Privation_Formalism_EPF x"

consts Priv_EPF_1_x_Evil_x_E_positive_x :: "i ⇒ bool"
consts Positive_EPF_1_x_Evil_x_E_positive_x :: "i ⇒ bool"
consts Restore_EPF_1_x_Evil_x_E_positive_x :: "i ⇒ bool"
consts mu_EPF_1_x_Evil_x_E_positive_x :: "i ⇒ real"
axiomatization where mu_EPF_1_x_Evil_x_E_positive_x_nonneg: "∀x. 0 ≤ mu_EPF_1_x_Evil_x_E_positive_x x"
  and restore_EPF_1_x_Evil_x_E_positive_x_iff_mu_zero: "∀x. mu_EPF_1_x_Evil_x_E_positive_x x = 0 ⟶ Restore_EPF_1_x_Evil_x_E_positive_x x"

consts Priv_EPF_2_x_Evil_x_y_Good_y_Dependent_on_x_y :: "i ⇒ bool"
consts Positive_EPF_2_x_Evil_x_y_Good_y_Dependent_on_x_y :: "i ⇒ bool"
consts Restore_EPF_2_x_Evil_x_y_Good_y_Dependent_on_x_y :: "i ⇒ bool"
consts mu_EPF_2_x_Evil_x_y_Good_y_Dependent_on_x_y :: "i ⇒ real"
axiomatization where mu_EPF_2_x_Evil_x_y_Good_y_Dependent_on_x_y_nonneg: "∀x. 0 ≤ mu_EPF_2_x_Evil_x_y_Good_y_Dependent_on_x_y x"
  and restore_EPF_2_x_Evil_x_y_Good_y_Dependent_on_x_y_iff_mu_zero: "∀x. mu_EPF_2_x_Evil_x_y_Good_y_Dependent_on_x_y x = 0 ⟶ Restore_EPF_2_x_Evil_x_y_Good_y_Dependent_on_x_y x"

consts Priv_EPF_3_x_Evil_x_Restorable_x :: "i ⇒ bool"
consts Positive_EPF_3_x_Evil_x_Restorable_x :: "i ⇒ bool"
consts Restore_EPF_3_x_Evil_x_Restorable_x :: "i ⇒ bool"
consts mu_EPF_3_x_Evil_x_Restorable_x :: "i ⇒ real"
axiomatization where mu_EPF_3_x_Evil_x_Restorable_x_nonneg: "∀x. 0 ≤ mu_EPF_3_x_Evil_x_Restorable_x x"
  and restore_EPF_3_x_Evil_x_Restorable_x_iff_mu_zero: "∀x. mu_EPF_3_x_Evil_x_Restorable_x x = 0 ⟶ Restore_EPF_3_x_Evil_x_Restorable_x x"

consts Priv_EPF_T1_x_Evil_x_Optimizable_x :: "i ⇒ bool"
consts Positive_EPF_T1_x_Evil_x_Optimizable_x :: "i ⇒ bool"
consts Restore_EPF_T1_x_Evil_x_Optimizable_x :: "i ⇒ bool"
consts mu_EPF_T1_x_Evil_x_Optimizable_x :: "i ⇒ real"
axiomatization where mu_EPF_T1_x_Evil_x_Optimizable_x_nonneg: "∀x. 0 ≤ mu_EPF_T1_x_Evil_x_Optimizable_x x"
  and restore_EPF_T1_x_Evil_x_Optimizable_x_iff_mu_zero: "∀x. mu_EPF_T1_x_Evil_x_Optimizable_x x = 0 ⟶ Restore_EPF_T1_x_Evil_x_Optimizable_x x"

consts Priv_EPF_T2_x_Evil_x_y_Good_y_Restores_y_x :: "i ⇒ bool"
consts Positive_EPF_T2_x_Evil_x_y_Good_y_Restores_y_x :: "i ⇒ bool"
consts Restore_EPF_T2_x_Evil_x_y_Good_y_Restores_y_x :: "i ⇒ bool"
consts mu_EPF_T2_x_Evil_x_y_Good_y_Restores_y_x :: "i ⇒ real"
axiomatization where mu_EPF_T2_x_Evil_x_y_Good_y_Restores_y_x_nonneg: "∀x. 0 ≤ mu_EPF_T2_x_Evil_x_y_Good_y_Restores_y_x x"
  and restore_EPF_T2_x_Evil_x_y_Good_y_Restores_y_x_iff_mu_zero: "∀x. mu_EPF_T2_x_Evil_x_y_Good_y_Restores_y_x x = 0 ⟶ Restore_EPF_T2_x_Evil_x_y_Good_y_Restores_y_x x"

consts Priv_2_Nothing_Privation_Formalism_NPF :: "i ⇒ bool"
consts Positive_2_Nothing_Privation_Formalism_NPF :: "i ⇒ bool"
consts Restore_2_Nothing_Privation_Formalism_NPF :: "i ⇒ bool"
consts mu_2_Nothing_Privation_Formalism_NPF :: "i ⇒ real"
axiomatization where mu_2_Nothing_Privation_Formalism_NPF_nonneg: "∀x. 0 ≤ mu_2_Nothing_Privation_Formalism_NPF x"
  and restore_2_Nothing_Privation_Formalism_NPF_iff_mu_zero: "∀x. mu_2_Nothing_Privation_Formalism_NPF x = 0 ⟶ Restore_2_Nothing_Privation_Formalism_NPF x"

consts Priv_NPF_2_x_Nothing_x_x_Boundary :: "i ⇒ bool"
consts Positive_NPF_2_x_Nothing_x_x_Boundary :: "i ⇒ bool"
consts Restore_NPF_2_x_Nothing_x_x_Boundary :: "i ⇒ bool"
consts mu_NPF_2_x_Nothing_x_x_Boundary :: "i ⇒ real"
axiomatization where mu_NPF_2_x_Nothing_x_x_Boundary_nonneg: "∀x. 0 ≤ mu_NPF_2_x_Nothing_x_x_Boundary x"
  and restore_NPF_2_x_Nothing_x_x_Boundary_iff_mu_zero: "∀x. mu_NPF_2_x_Nothing_x_x_Boundary x = 0 ⟶ Restore_NPF_2_x_Nothing_x_x_Boundary x"

consts Priv_NPF_3_x_Nothing_x_Creatable_ex_nihilo_x :: "i ⇒ bool"
consts Positive_NPF_3_x_Nothing_x_Creatable_ex_nihilo_x :: "i ⇒ bool"
consts Restore_NPF_3_x_Nothing_x_Creatable_ex_nihilo_x :: "i ⇒ bool"
consts mu_NPF_3_x_Nothing_x_Creatable_ex_nihilo_x :: "i ⇒ real"
axiomatization where mu_NPF_3_x_Nothing_x_Creatable_ex_nihilo_x_nonneg: "∀x. 0 ≤ mu_NPF_3_x_Nothing_x_Creatable_ex_nihilo_x x"
  and restore_NPF_3_x_Nothing_x_Creatable_ex_nihilo_x_iff_mu_zero: "∀x. mu_NPF_3_x_Nothing_x_Creatable_ex_nihilo_x x = 0 ⟶ Restore_NPF_3_x_Nothing_x_Creatable_ex_nihilo_x x"

consts Priv_NPF_T1_x_Nothing_x_Being_Optimizable_x :: "i ⇒ bool"
consts Positive_NPF_T1_x_Nothing_x_Being_Optimizable_x :: "i ⇒ bool"
consts Restore_NPF_T1_x_Nothing_x_Being_Optimizable_x :: "i ⇒ bool"
consts mu_NPF_T1_x_Nothing_x_Being_Optimizable_x :: "i ⇒ real"
axiomatization where mu_NPF_T1_x_Nothing_x_Being_Optimizable_x_nonneg: "∀x. 0 ≤ mu_NPF_T1_x_Nothing_x_Being_Optimizable_x x"
  and restore_NPF_T1_x_Nothing_x_Being_Optimizable_x_iff_mu_zero: "∀x. mu_NPF_T1_x_Nothing_x_Being_Optimizable_x x = 0 ⟶ Restore_NPF_T1_x_Nothing_x_Being_Optimizable_x x"

consts Priv_NPF_T2_x_Nothing_x_y_Being_y_Creates_from_y_x :: "i ⇒ bool"
consts Positive_NPF_T2_x_Nothing_x_y_Being_y_Creates_from_y_x :: "i ⇒ bool"
consts Restore_NPF_T2_x_Nothing_x_y_Being_y_Creates_from_y_x :: "i ⇒ bool"
consts mu_NPF_T2_x_Nothing_x_y_Being_y_Creates_from_y_x :: "i ⇒ real"
axiomatization where mu_NPF_T2_x_Nothing_x_y_Being_y_Creates_from_y_x_nonneg: "∀x. 0 ≤ mu_NPF_T2_x_Nothing_x_y_Being_y_Creates_from_y_x x"
  and restore_NPF_T2_x_Nothing_x_y_Being_y_Creates_from_y_x_iff_mu_zero: "∀x. mu_NPF_T2_x_Nothing_x_y_Being_y_Creates_from_y_x x = 0 ⟶ Restore_NPF_T2_x_Nothing_x_y_Being_y_Creates_from_y_x x"

consts Priv_NPF_T3_P_1_Nothing_has_maximum_privation_measure :: "i ⇒ bool"
consts Positive_NPF_T3_P_1_Nothing_has_maximum_privation_measure :: "i ⇒ bool"
consts Restore_NPF_T3_P_1_Nothing_has_maximum_privation_measure :: "i ⇒ bool"
consts mu_NPF_T3_P_1_Nothing_has_maximum_privation_measure :: "i ⇒ real"
axiomatization where mu_NPF_T3_P_1_Nothing_has_maximum_privation_measure_nonneg: "∀x. 0 ≤ mu_NPF_T3_P_1_Nothing_has_maximum_privation_measure x"
  and restore_NPF_T3_P_1_Nothing_has_maximum_privation_measure_iff_mu_zero: "∀x. mu_NPF_T3_P_1_Nothing_has_maximum_privation_measure x = 0 ⟶ Restore_NPF_T3_P_1_Nothing_has_maximum_privation_measure x"

consts Priv_NPF_T4_Nothing_lies_on_existence_boundary :: "i ⇒ bool"
consts Positive_NPF_T4_Nothing_lies_on_existence_boundary :: "i ⇒ bool"
consts Restore_NPF_T4_Nothing_lies_on_existence_boundary :: "i ⇒ bool"
consts mu_NPF_T4_Nothing_lies_on_existence_boundary :: "i ⇒ real"
axiomatization where mu_NPF_T4_Nothing_lies_on_existence_boundary_nonneg: "∀x. 0 ≤ mu_NPF_T4_Nothing_lies_on_existence_boundary x"
  and restore_NPF_T4_Nothing_lies_on_existence_boundary_iff_mu_zero: "∀x. mu_NPF_T4_Nothing_lies_on_existence_boundary x = 0 ⟶ Restore_NPF_T4_Nothing_lies_on_existence_boundary x"

consts Priv_3_Falsehood_Privation_Formalism_FPF :: "i ⇒ bool"
consts Positive_3_Falsehood_Privation_Formalism_FPF :: "i ⇒ bool"
consts Restore_3_Falsehood_Privation_Formalism_FPF :: "i ⇒ bool"
consts mu_3_Falsehood_Privation_Formalism_FPF :: "i ⇒ real"
axiomatization where mu_3_Falsehood_Privation_Formalism_FPF_nonneg: "∀x. 0 ≤ mu_3_Falsehood_Privation_Formalism_FPF x"
  and restore_3_Falsehood_Privation_Formalism_FPF_iff_mu_zero: "∀x. mu_3_Falsehood_Privation_Formalism_FPF x = 0 ⟶ Restore_3_Falsehood_Privation_Formalism_FPF x"

consts Priv_FPF_1_x_False_x_E_positive_truth_x :: "i ⇒ bool"
consts Positive_FPF_1_x_False_x_E_positive_truth_x :: "i ⇒ bool"
consts Restore_FPF_1_x_False_x_E_positive_truth_x :: "i ⇒ bool"
consts mu_FPF_1_x_False_x_E_positive_truth_x :: "i ⇒ real"
axiomatization where mu_FPF_1_x_False_x_E_positive_truth_x_nonneg: "∀x. 0 ≤ mu_FPF_1_x_False_x_E_positive_truth_x x"
  and restore_FPF_1_x_False_x_E_positive_truth_x_iff_mu_zero: "∀x. mu_FPF_1_x_False_x_E_positive_truth_x x = 0 ⟶ Restore_FPF_1_x_False_x_E_positive_truth_x x"

consts Priv_FPF_2_x_False_x_y_T_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Positive_FPF_2_x_False_x_y_T_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Restore_FPF_2_x_False_x_y_T_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts mu_FPF_2_x_False_x_y_T_y_Dependent_on_contrast_x_y :: "i ⇒ real"
axiomatization where mu_FPF_2_x_False_x_y_T_y_Dependent_on_contrast_x_y_nonneg: "∀x. 0 ≤ mu_FPF_2_x_False_x_y_T_y_Dependent_on_contrast_x_y x"
  and restore_FPF_2_x_False_x_y_T_y_Dependent_on_contrast_x_y_iff_mu_zero: "∀x. mu_FPF_2_x_False_x_y_T_y_Dependent_on_contrast_x_y x = 0 ⟶ Restore_FPF_2_x_False_x_y_T_y_Dependent_on_contrast_x_y x"

consts Priv_FPF_3_x_False_x_Truth_Restorable_x :: "i ⇒ bool"
consts Positive_FPF_3_x_False_x_Truth_Restorable_x :: "i ⇒ bool"
consts Restore_FPF_3_x_False_x_Truth_Restorable_x :: "i ⇒ bool"
consts mu_FPF_3_x_False_x_Truth_Restorable_x :: "i ⇒ real"
axiomatization where mu_FPF_3_x_False_x_Truth_Restorable_x_nonneg: "∀x. 0 ≤ mu_FPF_3_x_False_x_Truth_Restorable_x x"
  and restore_FPF_3_x_False_x_Truth_Restorable_x_iff_mu_zero: "∀x. mu_FPF_3_x_False_x_Truth_Restorable_x x = 0 ⟶ Restore_FPF_3_x_False_x_Truth_Restorable_x x"

consts Priv_FPF_T1_x_False_x_Truth_Optimizable_x :: "i ⇒ bool"
consts Positive_FPF_T1_x_False_x_Truth_Optimizable_x :: "i ⇒ bool"
consts Restore_FPF_T1_x_False_x_Truth_Optimizable_x :: "i ⇒ bool"
consts mu_FPF_T1_x_False_x_Truth_Optimizable_x :: "i ⇒ real"
axiomatization where mu_FPF_T1_x_False_x_Truth_Optimizable_x_nonneg: "∀x. 0 ≤ mu_FPF_T1_x_False_x_Truth_Optimizable_x x"
  and restore_FPF_T1_x_False_x_Truth_Optimizable_x_iff_mu_zero: "∀x. mu_FPF_T1_x_False_x_Truth_Optimizable_x x = 0 ⟶ Restore_FPF_T1_x_False_x_Truth_Optimizable_x x"

consts Priv_FPF_T2_x_False_x_y_T_y_Corrects_y_x :: "i ⇒ bool"
consts Positive_FPF_T2_x_False_x_y_T_y_Corrects_y_x :: "i ⇒ bool"
consts Restore_FPF_T2_x_False_x_y_T_y_Corrects_y_x :: "i ⇒ bool"
consts mu_FPF_T2_x_False_x_y_T_y_Corrects_y_x :: "i ⇒ real"
axiomatization where mu_FPF_T2_x_False_x_y_T_y_Corrects_y_x_nonneg: "∀x. 0 ≤ mu_FPF_T2_x_False_x_y_T_y_Corrects_y_x x"
  and restore_FPF_T2_x_False_x_y_T_y_Corrects_y_x_iff_mu_zero: "∀x. mu_FPF_T2_x_False_x_y_T_y_Corrects_y_x x = 0 ⟶ Restore_FPF_T2_x_False_x_y_T_y_Corrects_y_x x"

consts Priv_IV_ARCHITECTURAL_PRIVATIONS :: "i ⇒ bool"
consts Positive_IV_ARCHITECTURAL_PRIVATIONS :: "i ⇒ bool"
consts Restore_IV_ARCHITECTURAL_PRIVATIONS :: "i ⇒ bool"
consts mu_IV_ARCHITECTURAL_PRIVATIONS :: "i ⇒ real"
axiomatization where mu_IV_ARCHITECTURAL_PRIVATIONS_nonneg: "∀x. 0 ≤ mu_IV_ARCHITECTURAL_PRIVATIONS x"
  and restore_IV_ARCHITECTURAL_PRIVATIONS_iff_mu_zero: "∀x. mu_IV_ARCHITECTURAL_PRIVATIONS x = 0 ⟶ Restore_IV_ARCHITECTURAL_PRIVATIONS x"

consts Priv_1_Bridge_Privation_Formalism_BPF :: "i ⇒ bool"
consts Positive_1_Bridge_Privation_Formalism_BPF :: "i ⇒ bool"
consts Restore_1_Bridge_Privation_Formalism_BPF :: "i ⇒ bool"
consts mu_1_Bridge_Privation_Formalism_BPF :: "i ⇒ real"
axiomatization where mu_1_Bridge_Privation_Formalism_BPF_nonneg: "∀x. 0 ≤ mu_1_Bridge_Privation_Formalism_BPF x"
  and restore_1_Bridge_Privation_Formalism_BPF_iff_mu_zero: "∀x. mu_1_Bridge_Privation_Formalism_BPF x = 0 ⟶ Restore_1_Bridge_Privation_Formalism_BPF x"

consts Priv_BPF_1_x_Gapped_x_CanPerform_BRIDGE_operations_x :: "i ⇒ bool"
consts Positive_BPF_1_x_Gapped_x_CanPerform_BRIDGE_operations_x :: "i ⇒ bool"
consts Restore_BPF_1_x_Gapped_x_CanPerform_BRIDGE_operations_x :: "i ⇒ bool"
consts mu_BPF_1_x_Gapped_x_CanPerform_BRIDGE_operations_x :: "i ⇒ real"
axiomatization where mu_BPF_1_x_Gapped_x_CanPerform_BRIDGE_operations_x_nonneg: "∀x. 0 ≤ mu_BPF_1_x_Gapped_x_CanPerform_BRIDGE_operations_x x"
  and restore_BPF_1_x_Gapped_x_CanPerform_BRIDGE_operations_x_iff_mu_zero: "∀x. mu_BPF_1_x_Gapped_x_CanPerform_BRIDGE_operations_x x = 0 ⟶ Restore_BPF_1_x_Gapped_x_CanPerform_BRIDGE_operations_x x"

consts Priv_BPF_2_x_Gapped_x_y_BRIDGE_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Positive_BPF_2_x_Gapped_x_y_BRIDGE_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Restore_BPF_2_x_Gapped_x_y_BRIDGE_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts mu_BPF_2_x_Gapped_x_y_BRIDGE_y_Dependent_on_contrast_x_y :: "i ⇒ real"
axiomatization where mu_BPF_2_x_Gapped_x_y_BRIDGE_y_Dependent_on_contrast_x_y_nonneg: "∀x. 0 ≤ mu_BPF_2_x_Gapped_x_y_BRIDGE_y_Dependent_on_contrast_x_y x"
  and restore_BPF_2_x_Gapped_x_y_BRIDGE_y_Dependent_on_contrast_x_y_iff_mu_zero: "∀x. mu_BPF_2_x_Gapped_x_y_BRIDGE_y_Dependent_on_contrast_x_y x = 0 ⟶ Restore_BPF_2_x_Gapped_x_y_BRIDGE_y_Dependent_on_contrast_x_y x"

consts Priv_BPF_3_x_Gapped_x_BRIDGE_Restorable_x :: "i ⇒ bool"
consts Positive_BPF_3_x_Gapped_x_BRIDGE_Restorable_x :: "i ⇒ bool"
consts Restore_BPF_3_x_Gapped_x_BRIDGE_Restorable_x :: "i ⇒ bool"
consts mu_BPF_3_x_Gapped_x_BRIDGE_Restorable_x :: "i ⇒ real"
axiomatization where mu_BPF_3_x_Gapped_x_BRIDGE_Restorable_x_nonneg: "∀x. 0 ≤ mu_BPF_3_x_Gapped_x_BRIDGE_Restorable_x x"
  and restore_BPF_3_x_Gapped_x_BRIDGE_Restorable_x_iff_mu_zero: "∀x. mu_BPF_3_x_Gapped_x_BRIDGE_Restorable_x x = 0 ⟶ Restore_BPF_3_x_Gapped_x_BRIDGE_Restorable_x x"

consts Priv_BPF_T1_x_Gapped_x_Mapping_Optimizable_x :: "i ⇒ bool"
consts Positive_BPF_T1_x_Gapped_x_Mapping_Optimizable_x :: "i ⇒ bool"
consts Restore_BPF_T1_x_Gapped_x_Mapping_Optimizable_x :: "i ⇒ bool"
consts mu_BPF_T1_x_Gapped_x_Mapping_Optimizable_x :: "i ⇒ real"
axiomatization where mu_BPF_T1_x_Gapped_x_Mapping_Optimizable_x_nonneg: "∀x. 0 ≤ mu_BPF_T1_x_Gapped_x_Mapping_Optimizable_x x"
  and restore_BPF_T1_x_Gapped_x_Mapping_Optimizable_x_iff_mu_zero: "∀x. mu_BPF_T1_x_Gapped_x_Mapping_Optimizable_x x = 0 ⟶ Restore_BPF_T1_x_Gapped_x_Mapping_Optimizable_x x"

consts Priv_BPF_T2_x_Gapped_x_y_BRIDGE_y_Maps_for_y_x :: "i ⇒ bool"
consts Positive_BPF_T2_x_Gapped_x_y_BRIDGE_y_Maps_for_y_x :: "i ⇒ bool"
consts Restore_BPF_T2_x_Gapped_x_y_BRIDGE_y_Maps_for_y_x :: "i ⇒ bool"
consts mu_BPF_T2_x_Gapped_x_y_BRIDGE_y_Maps_for_y_x :: "i ⇒ real"
axiomatization where mu_BPF_T2_x_Gapped_x_y_BRIDGE_y_Maps_for_y_x_nonneg: "∀x. 0 ≤ mu_BPF_T2_x_Gapped_x_y_BRIDGE_y_Maps_for_y_x x"
  and restore_BPF_T2_x_Gapped_x_y_BRIDGE_y_Maps_for_y_x_iff_mu_zero: "∀x. mu_BPF_T2_x_Gapped_x_y_BRIDGE_y_Maps_for_y_x x = 0 ⟶ Restore_BPF_T2_x_Gapped_x_y_BRIDGE_y_Maps_for_y_x x"

consts Priv_BPF_T3_x_Gapped_x_Achieves_mathematical_metaphysical_continuity_x :: "i ⇒ bool"
consts Positive_BPF_T3_x_Gapped_x_Achieves_mathematical_metaphysical_continuity_x :: "i ⇒ bool"
consts Restore_BPF_T3_x_Gapped_x_Achieves_mathematical_metaphysical_continuity_x :: "i ⇒ bool"
consts mu_BPF_T3_x_Gapped_x_Achieves_mathematical_metaphysical_continuity_x :: "i ⇒ real"
axiomatization where mu_BPF_T3_x_Gapped_x_Achieves_mathematical_metaphysical_continuity_x_nonneg: "∀x. 0 ≤ mu_BPF_T3_x_Gapped_x_Achieves_mathematical_metaphysical_continuity_x x"
  and restore_BPF_T3_x_Gapped_x_Achieves_mathematical_metaphysical_continuity_x_iff_mu_zero: "∀x. mu_BPF_T3_x_Gapped_x_Achieves_mathematical_metaphysical_continuity_x x = 0 ⟶ Restore_BPF_T3_x_Gapped_x_Achieves_mathematical_metaphysical_continuity_x x"

consts Priv_2_Mind_Privation_Formalism_MPF :: "i ⇒ bool"
consts Positive_2_Mind_Privation_Formalism_MPF :: "i ⇒ bool"
consts Restore_2_Mind_Privation_Formalism_MPF :: "i ⇒ bool"
consts mu_2_Mind_Privation_Formalism_MPF :: "i ⇒ real"
axiomatization where mu_2_Mind_Privation_Formalism_MPF_nonneg: "∀x. 0 ≤ mu_2_Mind_Privation_Formalism_MPF x"
  and restore_2_Mind_Privation_Formalism_MPF_iff_mu_zero: "∀x. mu_2_Mind_Privation_Formalism_MPF x = 0 ⟶ Restore_2_Mind_Privation_Formalism_MPF x"

consts Priv_MPF_1_x_Mindless_x_CanPerform_MIND_operations_x :: "i ⇒ bool"
consts Positive_MPF_1_x_Mindless_x_CanPerform_MIND_operations_x :: "i ⇒ bool"
consts Restore_MPF_1_x_Mindless_x_CanPerform_MIND_operations_x :: "i ⇒ bool"
consts mu_MPF_1_x_Mindless_x_CanPerform_MIND_operations_x :: "i ⇒ real"
axiomatization where mu_MPF_1_x_Mindless_x_CanPerform_MIND_operations_x_nonneg: "∀x. 0 ≤ mu_MPF_1_x_Mindless_x_CanPerform_MIND_operations_x x"
  and restore_MPF_1_x_Mindless_x_CanPerform_MIND_operations_x_iff_mu_zero: "∀x. mu_MPF_1_x_Mindless_x_CanPerform_MIND_operations_x x = 0 ⟶ Restore_MPF_1_x_Mindless_x_CanPerform_MIND_operations_x x"

consts Priv_MPF_2_x_Mindless_x_y_MIND_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Positive_MPF_2_x_Mindless_x_y_MIND_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Restore_MPF_2_x_Mindless_x_y_MIND_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts mu_MPF_2_x_Mindless_x_y_MIND_y_Dependent_on_contrast_x_y :: "i ⇒ real"
axiomatization where mu_MPF_2_x_Mindless_x_y_MIND_y_Dependent_on_contrast_x_y_nonneg: "∀x. 0 ≤ mu_MPF_2_x_Mindless_x_y_MIND_y_Dependent_on_contrast_x_y x"
  and restore_MPF_2_x_Mindless_x_y_MIND_y_Dependent_on_contrast_x_y_iff_mu_zero: "∀x. mu_MPF_2_x_Mindless_x_y_MIND_y_Dependent_on_contrast_x_y x = 0 ⟶ Restore_MPF_2_x_Mindless_x_y_MIND_y_Dependent_on_contrast_x_y x"

consts Priv_MPF_3_x_Mindless_x_MIND_Restorable_x :: "i ⇒ bool"
consts Positive_MPF_3_x_Mindless_x_MIND_Restorable_x :: "i ⇒ bool"
consts Restore_MPF_3_x_Mindless_x_MIND_Restorable_x :: "i ⇒ bool"
consts mu_MPF_3_x_Mindless_x_MIND_Restorable_x :: "i ⇒ real"
axiomatization where mu_MPF_3_x_Mindless_x_MIND_Restorable_x_nonneg: "∀x. 0 ≤ mu_MPF_3_x_Mindless_x_MIND_Restorable_x x"
  and restore_MPF_3_x_Mindless_x_MIND_Restorable_x_iff_mu_zero: "∀x. mu_MPF_3_x_Mindless_x_MIND_Restorable_x x = 0 ⟶ Restore_MPF_3_x_Mindless_x_MIND_Restorable_x x"

consts Priv_MPF_T1_x_Mindless_x_Intelligence_Optimizable_x :: "i ⇒ bool"
consts Positive_MPF_T1_x_Mindless_x_Intelligence_Optimizable_x :: "i ⇒ bool"
consts Restore_MPF_T1_x_Mindless_x_Intelligence_Optimizable_x :: "i ⇒ bool"
consts mu_MPF_T1_x_Mindless_x_Intelligence_Optimizable_x :: "i ⇒ real"
axiomatization where mu_MPF_T1_x_Mindless_x_Intelligence_Optimizable_x_nonneg: "∀x. 0 ≤ mu_MPF_T1_x_Mindless_x_Intelligence_Optimizable_x x"
  and restore_MPF_T1_x_Mindless_x_Intelligence_Optimizable_x_iff_mu_zero: "∀x. mu_MPF_T1_x_Mindless_x_Intelligence_Optimizable_x x = 0 ⟶ Restore_MPF_T1_x_Mindless_x_Intelligence_Optimizable_x x"

consts Priv_MPF_T2_x_Mindless_x_y_MIND_y_Thinks_for_y_x :: "i ⇒ bool"
consts Positive_MPF_T2_x_Mindless_x_y_MIND_y_Thinks_for_y_x :: "i ⇒ bool"
consts Restore_MPF_T2_x_Mindless_x_y_MIND_y_Thinks_for_y_x :: "i ⇒ bool"
consts mu_MPF_T2_x_Mindless_x_y_MIND_y_Thinks_for_y_x :: "i ⇒ real"
axiomatization where mu_MPF_T2_x_Mindless_x_y_MIND_y_Thinks_for_y_x_nonneg: "∀x. 0 ≤ mu_MPF_T2_x_Mindless_x_y_MIND_y_Thinks_for_y_x x"
  and restore_MPF_T2_x_Mindless_x_y_MIND_y_Thinks_for_y_x_iff_mu_zero: "∀x. mu_MPF_T2_x_Mindless_x_y_MIND_y_Thinks_for_y_x x = 0 ⟶ Restore_MPF_T2_x_Mindless_x_y_MIND_y_Thinks_for_y_x x"

consts Priv_MPF_T3_x_Mindless_x_Achieves_rational_coordination_x :: "i ⇒ bool"
consts Positive_MPF_T3_x_Mindless_x_Achieves_rational_coordination_x :: "i ⇒ bool"
consts Restore_MPF_T3_x_Mindless_x_Achieves_rational_coordination_x :: "i ⇒ bool"
consts mu_MPF_T3_x_Mindless_x_Achieves_rational_coordination_x :: "i ⇒ real"
axiomatization where mu_MPF_T3_x_Mindless_x_Achieves_rational_coordination_x_nonneg: "∀x. 0 ≤ mu_MPF_T3_x_Mindless_x_Achieves_rational_coordination_x x"
  and restore_MPF_T3_x_Mindless_x_Achieves_rational_coordination_x_iff_mu_zero: "∀x. mu_MPF_T3_x_Mindless_x_Achieves_rational_coordination_x x = 0 ⟶ Restore_MPF_T3_x_Mindless_x_Achieves_rational_coordination_x x"

consts Priv_3_Sign_Privation_Formalism_SPF :: "i ⇒ bool"
consts Positive_3_Sign_Privation_Formalism_SPF :: "i ⇒ bool"
consts Restore_3_Sign_Privation_Formalism_SPF :: "i ⇒ bool"
consts mu_3_Sign_Privation_Formalism_SPF :: "i ⇒ real"
axiomatization where mu_3_Sign_Privation_Formalism_SPF_nonneg: "∀x. 0 ≤ mu_3_Sign_Privation_Formalism_SPF x"
  and restore_3_Sign_Privation_Formalism_SPF_iff_mu_zero: "∀x. mu_3_Sign_Privation_Formalism_SPF x = 0 ⟶ Restore_3_Sign_Privation_Formalism_SPF x"

consts Priv_SPF_1_x_Sequential_x_CanPerform_SIGN_operations_x :: "i ⇒ bool"
consts Positive_SPF_1_x_Sequential_x_CanPerform_SIGN_operations_x :: "i ⇒ bool"
consts Restore_SPF_1_x_Sequential_x_CanPerform_SIGN_operations_x :: "i ⇒ bool"
consts mu_SPF_1_x_Sequential_x_CanPerform_SIGN_operations_x :: "i ⇒ real"
axiomatization where mu_SPF_1_x_Sequential_x_CanPerform_SIGN_operations_x_nonneg: "∀x. 0 ≤ mu_SPF_1_x_Sequential_x_CanPerform_SIGN_operations_x x"
  and restore_SPF_1_x_Sequential_x_CanPerform_SIGN_operations_x_iff_mu_zero: "∀x. mu_SPF_1_x_Sequential_x_CanPerform_SIGN_operations_x x = 0 ⟶ Restore_SPF_1_x_Sequential_x_CanPerform_SIGN_operations_x x"

consts Priv_SPF_2_x_Sequential_x_y_SIGN_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Positive_SPF_2_x_Sequential_x_y_SIGN_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Restore_SPF_2_x_Sequential_x_y_SIGN_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts mu_SPF_2_x_Sequential_x_y_SIGN_y_Dependent_on_contrast_x_y :: "i ⇒ real"
axiomatization where mu_SPF_2_x_Sequential_x_y_SIGN_y_Dependent_on_contrast_x_y_nonneg: "∀x. 0 ≤ mu_SPF_2_x_Sequential_x_y_SIGN_y_Dependent_on_contrast_x_y x"
  and restore_SPF_2_x_Sequential_x_y_SIGN_y_Dependent_on_contrast_x_y_iff_mu_zero: "∀x. mu_SPF_2_x_Sequential_x_y_SIGN_y_Dependent_on_contrast_x_y x = 0 ⟶ Restore_SPF_2_x_Sequential_x_y_SIGN_y_Dependent_on_contrast_x_y x"

consts Priv_SPF_3_x_Sequential_x_SIGN_Restorable_x :: "i ⇒ bool"
consts Positive_SPF_3_x_Sequential_x_SIGN_Restorable_x :: "i ⇒ bool"
consts Restore_SPF_3_x_Sequential_x_SIGN_Restorable_x :: "i ⇒ bool"
consts mu_SPF_3_x_Sequential_x_SIGN_Restorable_x :: "i ⇒ real"
axiomatization where mu_SPF_3_x_Sequential_x_SIGN_Restorable_x_nonneg: "∀x. 0 ≤ mu_SPF_3_x_Sequential_x_SIGN_Restorable_x x"
  and restore_SPF_3_x_Sequential_x_SIGN_Restorable_x_iff_mu_zero: "∀x. mu_SPF_3_x_Sequential_x_SIGN_Restorable_x x = 0 ⟶ Restore_SPF_3_x_Sequential_x_SIGN_Restorable_x x"

consts Priv_SPF_T1_x_Sequential_x_Instantiation_Optimizable_x :: "i ⇒ bool"
consts Positive_SPF_T1_x_Sequential_x_Instantiation_Optimizable_x :: "i ⇒ bool"
consts Restore_SPF_T1_x_Sequential_x_Instantiation_Optimizable_x :: "i ⇒ bool"
consts mu_SPF_T1_x_Sequential_x_Instantiation_Optimizable_x :: "i ⇒ real"
axiomatization where mu_SPF_T1_x_Sequential_x_Instantiation_Optimizable_x_nonneg: "∀x. 0 ≤ mu_SPF_T1_x_Sequential_x_Instantiation_Optimizable_x x"
  and restore_SPF_T1_x_Sequential_x_Instantiation_Optimizable_x_iff_mu_zero: "∀x. mu_SPF_T1_x_Sequential_x_Instantiation_Optimizable_x x = 0 ⟶ Restore_SPF_T1_x_Sequential_x_Instantiation_Optimizable_x x"

consts Priv_SPF_T2_x_Sequential_x_y_SIGN_y_Instantiates_for_y_x :: "i ⇒ bool"
consts Positive_SPF_T2_x_Sequential_x_y_SIGN_y_Instantiates_for_y_x :: "i ⇒ bool"
consts Restore_SPF_T2_x_Sequential_x_y_SIGN_y_Instantiates_for_y_x :: "i ⇒ bool"
consts mu_SPF_T2_x_Sequential_x_y_SIGN_y_Instantiates_for_y_x :: "i ⇒ real"
axiomatization where mu_SPF_T2_x_Sequential_x_y_SIGN_y_Instantiates_for_y_x_nonneg: "∀x. 0 ≤ mu_SPF_T2_x_Sequential_x_y_SIGN_y_Instantiates_for_y_x x"
  and restore_SPF_T2_x_Sequential_x_y_SIGN_y_Instantiates_for_y_x_iff_mu_zero: "∀x. mu_SPF_T2_x_Sequential_x_y_SIGN_y_Instantiates_for_y_x x = 0 ⟶ Restore_SPF_T2_x_Sequential_x_y_SIGN_y_Instantiates_for_y_x x"

consts Priv_SPF_T3_x_Sequential_x_Achieves_simultaneous_instantiation_x :: "i ⇒ bool"
consts Positive_SPF_T3_x_Sequential_x_Achieves_simultaneous_instantiation_x :: "i ⇒ bool"
consts Restore_SPF_T3_x_Sequential_x_Achieves_simultaneous_instantiation_x :: "i ⇒ bool"
consts mu_SPF_T3_x_Sequential_x_Achieves_simultaneous_instantiation_x :: "i ⇒ real"
axiomatization where mu_SPF_T3_x_Sequential_x_Achieves_simultaneous_instantiation_x_nonneg: "∀x. 0 ≤ mu_SPF_T3_x_Sequential_x_Achieves_simultaneous_instantiation_x x"
  and restore_SPF_T3_x_Sequential_x_Achieves_simultaneous_instantiation_x_iff_mu_zero: "∀x. mu_SPF_T3_x_Sequential_x_Achieves_simultaneous_instantiation_x x = 0 ⟶ Restore_SPF_T3_x_Sequential_x_Achieves_simultaneous_instantiation_x x"

consts Priv_4_Mesh_Privation_Formalism_MEPF :: "i ⇒ bool"
consts Positive_4_Mesh_Privation_Formalism_MEPF :: "i ⇒ bool"
consts Restore_4_Mesh_Privation_Formalism_MEPF :: "i ⇒ bool"
consts mu_4_Mesh_Privation_Formalism_MEPF :: "i ⇒ real"
axiomatization where mu_4_Mesh_Privation_Formalism_MEPF_nonneg: "∀x. 0 ≤ mu_4_Mesh_Privation_Formalism_MEPF x"
  and restore_4_Mesh_Privation_Formalism_MEPF_iff_mu_zero: "∀x. mu_4_Mesh_Privation_Formalism_MEPF x = 0 ⟶ Restore_4_Mesh_Privation_Formalism_MEPF x"

consts Priv_MEPF_1_x_Fragmented_x_CanPerform_MESH_operations_x :: "i ⇒ bool"
consts Positive_MEPF_1_x_Fragmented_x_CanPerform_MESH_operations_x :: "i ⇒ bool"
consts Restore_MEPF_1_x_Fragmented_x_CanPerform_MESH_operations_x :: "i ⇒ bool"
consts mu_MEPF_1_x_Fragmented_x_CanPerform_MESH_operations_x :: "i ⇒ real"
axiomatization where mu_MEPF_1_x_Fragmented_x_CanPerform_MESH_operations_x_nonneg: "∀x. 0 ≤ mu_MEPF_1_x_Fragmented_x_CanPerform_MESH_operations_x x"
  and restore_MEPF_1_x_Fragmented_x_CanPerform_MESH_operations_x_iff_mu_zero: "∀x. mu_MEPF_1_x_Fragmented_x_CanPerform_MESH_operations_x x = 0 ⟶ Restore_MEPF_1_x_Fragmented_x_CanPerform_MESH_operations_x x"

consts Priv_MEPF_2_x_Fragmented_x_y_MESH_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Positive_MEPF_2_x_Fragmented_x_y_MESH_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Restore_MEPF_2_x_Fragmented_x_y_MESH_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts mu_MEPF_2_x_Fragmented_x_y_MESH_y_Dependent_on_contrast_x_y :: "i ⇒ real"
axiomatization where mu_MEPF_2_x_Fragmented_x_y_MESH_y_Dependent_on_contrast_x_y_nonneg: "∀x. 0 ≤ mu_MEPF_2_x_Fragmented_x_y_MESH_y_Dependent_on_contrast_x_y x"
  and restore_MEPF_2_x_Fragmented_x_y_MESH_y_Dependent_on_contrast_x_y_iff_mu_zero: "∀x. mu_MEPF_2_x_Fragmented_x_y_MESH_y_Dependent_on_contrast_x_y x = 0 ⟶ Restore_MEPF_2_x_Fragmented_x_y_MESH_y_Dependent_on_contrast_x_y x"

consts Priv_MEPF_3_x_Fragmented_x_MESH_Restorable_x :: "i ⇒ bool"
consts Positive_MEPF_3_x_Fragmented_x_MESH_Restorable_x :: "i ⇒ bool"
consts Restore_MEPF_3_x_Fragmented_x_MESH_Restorable_x :: "i ⇒ bool"
consts mu_MEPF_3_x_Fragmented_x_MESH_Restorable_x :: "i ⇒ real"
axiomatization where mu_MEPF_3_x_Fragmented_x_MESH_Restorable_x_nonneg: "∀x. 0 ≤ mu_MEPF_3_x_Fragmented_x_MESH_Restorable_x x"
  and restore_MEPF_3_x_Fragmented_x_MESH_Restorable_x_iff_mu_zero: "∀x. mu_MEPF_3_x_Fragmented_x_MESH_Restorable_x x = 0 ⟶ Restore_MEPF_3_x_Fragmented_x_MESH_Restorable_x x"

consts Priv_MEPF_T1_x_Fragmented_x_Structure_Optimizable_x :: "i ⇒ bool"
consts Positive_MEPF_T1_x_Fragmented_x_Structure_Optimizable_x :: "i ⇒ bool"
consts Restore_MEPF_T1_x_Fragmented_x_Structure_Optimizable_x :: "i ⇒ bool"
consts mu_MEPF_T1_x_Fragmented_x_Structure_Optimizable_x :: "i ⇒ real"
axiomatization where mu_MEPF_T1_x_Fragmented_x_Structure_Optimizable_x_nonneg: "∀x. 0 ≤ mu_MEPF_T1_x_Fragmented_x_Structure_Optimizable_x x"
  and restore_MEPF_T1_x_Fragmented_x_Structure_Optimizable_x_iff_mu_zero: "∀x. mu_MEPF_T1_x_Fragmented_x_Structure_Optimizable_x x = 0 ⟶ Restore_MEPF_T1_x_Fragmented_x_Structure_Optimizable_x x"

consts Priv_MEPF_T2_x_Fragmented_x_y_MESH_y_Structures_for_y_x :: "i ⇒ bool"
consts Positive_MEPF_T2_x_Fragmented_x_y_MESH_y_Structures_for_y_x :: "i ⇒ bool"
consts Restore_MEPF_T2_x_Fragmented_x_y_MESH_y_Structures_for_y_x :: "i ⇒ bool"
consts mu_MEPF_T2_x_Fragmented_x_y_MESH_y_Structures_for_y_x :: "i ⇒ real"
axiomatization where mu_MEPF_T2_x_Fragmented_x_y_MESH_y_Structures_for_y_x_nonneg: "∀x. 0 ≤ mu_MEPF_T2_x_Fragmented_x_y_MESH_y_Structures_for_y_x x"
  and restore_MEPF_T2_x_Fragmented_x_y_MESH_y_Structures_for_y_x_iff_mu_zero: "∀x. mu_MEPF_T2_x_Fragmented_x_y_MESH_y_Structures_for_y_x x = 0 ⟶ Restore_MEPF_T2_x_Fragmented_x_y_MESH_y_Structures_for_y_x x"

consts Priv_MEPF_T3_x_Fragmented_x_Achieves_coherent_synchronization_x :: "i ⇒ bool"
consts Positive_MEPF_T3_x_Fragmented_x_Achieves_coherent_synchronization_x :: "i ⇒ bool"
consts Restore_MEPF_T3_x_Fragmented_x_Achieves_coherent_synchronization_x :: "i ⇒ bool"
consts mu_MEPF_T3_x_Fragmented_x_Achieves_coherent_synchronization_x :: "i ⇒ real"
axiomatization where mu_MEPF_T3_x_Fragmented_x_Achieves_coherent_synchronization_x_nonneg: "∀x. 0 ≤ mu_MEPF_T3_x_Fragmented_x_Achieves_coherent_synchronization_x x"
  and restore_MEPF_T3_x_Fragmented_x_Achieves_coherent_synchronization_x_iff_mu_zero: "∀x. mu_MEPF_T3_x_Fragmented_x_Achieves_coherent_synchronization_x x = 0 ⟶ Restore_MEPF_T3_x_Fragmented_x_Achieves_coherent_synchronization_x x"

consts Priv_V_OPERATIONAL_PRIVATIONS :: "i ⇒ bool"
consts Positive_V_OPERATIONAL_PRIVATIONS :: "i ⇒ bool"
consts Restore_V_OPERATIONAL_PRIVATIONS :: "i ⇒ bool"
consts mu_V_OPERATIONAL_PRIVATIONS :: "i ⇒ real"
axiomatization where mu_V_OPERATIONAL_PRIVATIONS_nonneg: "∀x. 0 ≤ mu_V_OPERATIONAL_PRIVATIONS x"
  and restore_V_OPERATIONAL_PRIVATIONS_iff_mu_zero: "∀x. mu_V_OPERATIONAL_PRIVATIONS x = 0 ⟶ Restore_V_OPERATIONAL_PRIVATIONS x"

consts Priv_1_Relational_Privation_Formalism_RPF :: "i ⇒ bool"
consts Positive_1_Relational_Privation_Formalism_RPF :: "i ⇒ bool"
consts Restore_1_Relational_Privation_Formalism_RPF :: "i ⇒ bool"
consts mu_1_Relational_Privation_Formalism_RPF :: "i ⇒ real"
axiomatization where mu_1_Relational_Privation_Formalism_RPF_nonneg: "∀x. 0 ≤ mu_1_Relational_Privation_Formalism_RPF x"
  and restore_1_Relational_Privation_Formalism_RPF_iff_mu_zero: "∀x. mu_1_Relational_Privation_Formalism_RPF x = 0 ⟶ Restore_1_Relational_Privation_Formalism_RPF x"

consts Priv_RPF_1_x_Isolated_x_E_relational_x :: "i ⇒ bool"
consts Positive_RPF_1_x_Isolated_x_E_relational_x :: "i ⇒ bool"
consts Restore_RPF_1_x_Isolated_x_E_relational_x :: "i ⇒ bool"
consts mu_RPF_1_x_Isolated_x_E_relational_x :: "i ⇒ real"
axiomatization where mu_RPF_1_x_Isolated_x_E_relational_x_nonneg: "∀x. 0 ≤ mu_RPF_1_x_Isolated_x_E_relational_x x"
  and restore_RPF_1_x_Isolated_x_E_relational_x_iff_mu_zero: "∀x. mu_RPF_1_x_Isolated_x_E_relational_x x = 0 ⟶ Restore_RPF_1_x_Isolated_x_E_relational_x x"

consts Priv_RPF_2_x_Isolated_x_y_R_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Positive_RPF_2_x_Isolated_x_y_R_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Restore_RPF_2_x_Isolated_x_y_R_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts mu_RPF_2_x_Isolated_x_y_R_y_Dependent_on_contrast_x_y :: "i ⇒ real"
axiomatization where mu_RPF_2_x_Isolated_x_y_R_y_Dependent_on_contrast_x_y_nonneg: "∀x. 0 ≤ mu_RPF_2_x_Isolated_x_y_R_y_Dependent_on_contrast_x_y x"
  and restore_RPF_2_x_Isolated_x_y_R_y_Dependent_on_contrast_x_y_iff_mu_zero: "∀x. mu_RPF_2_x_Isolated_x_y_R_y_Dependent_on_contrast_x_y x = 0 ⟶ Restore_RPF_2_x_Isolated_x_y_R_y_Dependent_on_contrast_x_y x"

consts Priv_RPF_3_x_Isolated_x_Relation_Restorable_x :: "i ⇒ bool"
consts Positive_RPF_3_x_Isolated_x_Relation_Restorable_x :: "i ⇒ bool"
consts Restore_RPF_3_x_Isolated_x_Relation_Restorable_x :: "i ⇒ bool"
consts mu_RPF_3_x_Isolated_x_Relation_Restorable_x :: "i ⇒ real"
axiomatization where mu_RPF_3_x_Isolated_x_Relation_Restorable_x_nonneg: "∀x. 0 ≤ mu_RPF_3_x_Isolated_x_Relation_Restorable_x x"
  and restore_RPF_3_x_Isolated_x_Relation_Restorable_x_iff_mu_zero: "∀x. mu_RPF_3_x_Isolated_x_Relation_Restorable_x x = 0 ⟶ Restore_RPF_3_x_Isolated_x_Relation_Restorable_x x"

consts Priv_RPF_T1_x_Isolated_x_Connection_Optimizable_x :: "i ⇒ bool"
consts Positive_RPF_T1_x_Isolated_x_Connection_Optimizable_x :: "i ⇒ bool"
consts Restore_RPF_T1_x_Isolated_x_Connection_Optimizable_x :: "i ⇒ bool"
consts mu_RPF_T1_x_Isolated_x_Connection_Optimizable_x :: "i ⇒ real"
axiomatization where mu_RPF_T1_x_Isolated_x_Connection_Optimizable_x_nonneg: "∀x. 0 ≤ mu_RPF_T1_x_Isolated_x_Connection_Optimizable_x x"
  and restore_RPF_T1_x_Isolated_x_Connection_Optimizable_x_iff_mu_zero: "∀x. mu_RPF_T1_x_Isolated_x_Connection_Optimizable_x x = 0 ⟶ Restore_RPF_T1_x_Isolated_x_Connection_Optimizable_x x"

consts Priv_RPF_T2_x_Isolated_x_y_R_y_Connects_y_x :: "i ⇒ bool"
consts Positive_RPF_T2_x_Isolated_x_y_R_y_Connects_y_x :: "i ⇒ bool"
consts Restore_RPF_T2_x_Isolated_x_y_R_y_Connects_y_x :: "i ⇒ bool"
consts mu_RPF_T2_x_Isolated_x_y_R_y_Connects_y_x :: "i ⇒ real"
axiomatization where mu_RPF_T2_x_Isolated_x_y_R_y_Connects_y_x_nonneg: "∀x. 0 ≤ mu_RPF_T2_x_Isolated_x_y_R_y_Connects_y_x x"
  and restore_RPF_T2_x_Isolated_x_y_R_y_Connects_y_x_iff_mu_zero: "∀x. mu_RPF_T2_x_Isolated_x_y_R_y_Connects_y_x x = 0 ⟶ Restore_RPF_T2_x_Isolated_x_y_R_y_Connects_y_x x"

consts Priv_RPF_T3_x_Isolated_x_Achieves_communal_participation_x :: "i ⇒ bool"
consts Positive_RPF_T3_x_Isolated_x_Achieves_communal_participation_x :: "i ⇒ bool"
consts Restore_RPF_T3_x_Isolated_x_Achieves_communal_participation_x :: "i ⇒ bool"
consts mu_RPF_T3_x_Isolated_x_Achieves_communal_participation_x :: "i ⇒ real"
axiomatization where mu_RPF_T3_x_Isolated_x_Achieves_communal_participation_x_nonneg: "∀x. 0 ≤ mu_RPF_T3_x_Isolated_x_Achieves_communal_participation_x x"
  and restore_RPF_T3_x_Isolated_x_Achieves_communal_participation_x_iff_mu_zero: "∀x. mu_RPF_T3_x_Isolated_x_Achieves_communal_participation_x x = 0 ⟶ Restore_RPF_T3_x_Isolated_x_Achieves_communal_participation_x x"

consts Priv_2_Temporal_Privation_Formalism_TPF :: "i ⇒ bool"
consts Positive_2_Temporal_Privation_Formalism_TPF :: "i ⇒ bool"
consts Restore_2_Temporal_Privation_Formalism_TPF :: "i ⇒ bool"
consts mu_2_Temporal_Privation_Formalism_TPF :: "i ⇒ real"
axiomatization where mu_2_Temporal_Privation_Formalism_TPF_nonneg: "∀x. 0 ≤ mu_2_Temporal_Privation_Formalism_TPF x"
  and restore_2_Temporal_Privation_Formalism_TPF_iff_mu_zero: "∀x. mu_2_Temporal_Privation_Formalism_TPF x = 0 ⟶ Restore_2_Temporal_Privation_Formalism_TPF x"

consts Priv_TPF_1_x_Atemporal_x_E_temporal_x :: "i ⇒ bool"
consts Positive_TPF_1_x_Atemporal_x_E_temporal_x :: "i ⇒ bool"
consts Restore_TPF_1_x_Atemporal_x_E_temporal_x :: "i ⇒ bool"
consts mu_TPF_1_x_Atemporal_x_E_temporal_x :: "i ⇒ real"
axiomatization where mu_TPF_1_x_Atemporal_x_E_temporal_x_nonneg: "∀x. 0 ≤ mu_TPF_1_x_Atemporal_x_E_temporal_x x"
  and restore_TPF_1_x_Atemporal_x_E_temporal_x_iff_mu_zero: "∀x. mu_TPF_1_x_Atemporal_x_E_temporal_x x = 0 ⟶ Restore_TPF_1_x_Atemporal_x_E_temporal_x x"

consts Priv_TPF_2_x_Atemporal_x_y_T_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Positive_TPF_2_x_Atemporal_x_y_T_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Restore_TPF_2_x_Atemporal_x_y_T_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts mu_TPF_2_x_Atemporal_x_y_T_y_Dependent_on_contrast_x_y :: "i ⇒ real"
axiomatization where mu_TPF_2_x_Atemporal_x_y_T_y_Dependent_on_contrast_x_y_nonneg: "∀x. 0 ≤ mu_TPF_2_x_Atemporal_x_y_T_y_Dependent_on_contrast_x_y x"
  and restore_TPF_2_x_Atemporal_x_y_T_y_Dependent_on_contrast_x_y_iff_mu_zero: "∀x. mu_TPF_2_x_Atemporal_x_y_T_y_Dependent_on_contrast_x_y x = 0 ⟶ Restore_TPF_2_x_Atemporal_x_y_T_y_Dependent_on_contrast_x_y x"

consts Priv_TPF_3_x_Atemporal_x_Temporal_Restorable_x :: "i ⇒ bool"
consts Positive_TPF_3_x_Atemporal_x_Temporal_Restorable_x :: "i ⇒ bool"
consts Restore_TPF_3_x_Atemporal_x_Temporal_Restorable_x :: "i ⇒ bool"
consts mu_TPF_3_x_Atemporal_x_Temporal_Restorable_x :: "i ⇒ real"
axiomatization where mu_TPF_3_x_Atemporal_x_Temporal_Restorable_x_nonneg: "∀x. 0 ≤ mu_TPF_3_x_Atemporal_x_Temporal_Restorable_x x"
  and restore_TPF_3_x_Atemporal_x_Temporal_Restorable_x_iff_mu_zero: "∀x. mu_TPF_3_x_Atemporal_x_Temporal_Restorable_x x = 0 ⟶ Restore_TPF_3_x_Atemporal_x_Temporal_Restorable_x x"

consts Priv_TPF_T1_x_Atemporal_x_Temporal_Optimizable_x :: "i ⇒ bool"
consts Positive_TPF_T1_x_Atemporal_x_Temporal_Optimizable_x :: "i ⇒ bool"
consts Restore_TPF_T1_x_Atemporal_x_Temporal_Optimizable_x :: "i ⇒ bool"
consts mu_TPF_T1_x_Atemporal_x_Temporal_Optimizable_x :: "i ⇒ real"
axiomatization where mu_TPF_T1_x_Atemporal_x_Temporal_Optimizable_x_nonneg: "∀x. 0 ≤ mu_TPF_T1_x_Atemporal_x_Temporal_Optimizable_x x"
  and restore_TPF_T1_x_Atemporal_x_Temporal_Optimizable_x_iff_mu_zero: "∀x. mu_TPF_T1_x_Atemporal_x_Temporal_Optimizable_x x = 0 ⟶ Restore_TPF_T1_x_Atemporal_x_Temporal_Optimizable_x x"

consts Priv_TPF_T2_x_Atemporal_x_y_T_y_Temporalizes_y_x :: "i ⇒ bool"
consts Positive_TPF_T2_x_Atemporal_x_y_T_y_Temporalizes_y_x :: "i ⇒ bool"
consts Restore_TPF_T2_x_Atemporal_x_y_T_y_Temporalizes_y_x :: "i ⇒ bool"
consts mu_TPF_T2_x_Atemporal_x_y_T_y_Temporalizes_y_x :: "i ⇒ real"
axiomatization where mu_TPF_T2_x_Atemporal_x_y_T_y_Temporalizes_y_x_nonneg: "∀x. 0 ≤ mu_TPF_T2_x_Atemporal_x_y_T_y_Temporalizes_y_x x"
  and restore_TPF_T2_x_Atemporal_x_y_T_y_Temporalizes_y_x_iff_mu_zero: "∀x. mu_TPF_T2_x_Atemporal_x_y_T_y_Temporalizes_y_x x = 0 ⟶ Restore_TPF_T2_x_Atemporal_x_y_T_y_Temporalizes_y_x x"

consts Priv_TPF_T3_x_Atemporal_x_Achieves_temporal_coherence_x :: "i ⇒ bool"
consts Positive_TPF_T3_x_Atemporal_x_Achieves_temporal_coherence_x :: "i ⇒ bool"
consts Restore_TPF_T3_x_Atemporal_x_Achieves_temporal_coherence_x :: "i ⇒ bool"
consts mu_TPF_T3_x_Atemporal_x_Achieves_temporal_coherence_x :: "i ⇒ real"
axiomatization where mu_TPF_T3_x_Atemporal_x_Achieves_temporal_coherence_x_nonneg: "∀x. 0 ≤ mu_TPF_T3_x_Atemporal_x_Achieves_temporal_coherence_x x"
  and restore_TPF_T3_x_Atemporal_x_Achieves_temporal_coherence_x_iff_mu_zero: "∀x. mu_TPF_T3_x_Atemporal_x_Achieves_temporal_coherence_x x = 0 ⟶ Restore_TPF_T3_x_Atemporal_x_Achieves_temporal_coherence_x x"

consts Priv_3_Causal_Privation_Formalism_CPF :: "i ⇒ bool"
consts Positive_3_Causal_Privation_Formalism_CPF :: "i ⇒ bool"
consts Restore_3_Causal_Privation_Formalism_CPF :: "i ⇒ bool"
consts mu_3_Causal_Privation_Formalism_CPF :: "i ⇒ real"
axiomatization where mu_3_Causal_Privation_Formalism_CPF_nonneg: "∀x. 0 ≤ mu_3_Causal_Privation_Formalism_CPF x"
  and restore_3_Causal_Privation_Formalism_CPF_iff_mu_zero: "∀x. mu_3_Causal_Privation_Formalism_CPF x = 0 ⟶ Restore_3_Causal_Privation_Formalism_CPF x"

consts Priv_CPF_1_x_CausallyGapped_x_E_causal_x :: "i ⇒ bool"
consts Positive_CPF_1_x_CausallyGapped_x_E_causal_x :: "i ⇒ bool"
consts Restore_CPF_1_x_CausallyGapped_x_E_causal_x :: "i ⇒ bool"
consts mu_CPF_1_x_CausallyGapped_x_E_causal_x :: "i ⇒ real"
axiomatization where mu_CPF_1_x_CausallyGapped_x_E_causal_x_nonneg: "∀x. 0 ≤ mu_CPF_1_x_CausallyGapped_x_E_causal_x x"
  and restore_CPF_1_x_CausallyGapped_x_E_causal_x_iff_mu_zero: "∀x. mu_CPF_1_x_CausallyGapped_x_E_causal_x x = 0 ⟶ Restore_CPF_1_x_CausallyGapped_x_E_causal_x x"

consts Priv_CPF_2_x_CausallyGapped_x_y_C_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Positive_CPF_2_x_CausallyGapped_x_y_C_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Restore_CPF_2_x_CausallyGapped_x_y_C_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts mu_CPF_2_x_CausallyGapped_x_y_C_y_Dependent_on_contrast_x_y :: "i ⇒ real"
axiomatization where mu_CPF_2_x_CausallyGapped_x_y_C_y_Dependent_on_contrast_x_y_nonneg: "∀x. 0 ≤ mu_CPF_2_x_CausallyGapped_x_y_C_y_Dependent_on_contrast_x_y x"
  and restore_CPF_2_x_CausallyGapped_x_y_C_y_Dependent_on_contrast_x_y_iff_mu_zero: "∀x. mu_CPF_2_x_CausallyGapped_x_y_C_y_Dependent_on_contrast_x_y x = 0 ⟶ Restore_CPF_2_x_CausallyGapped_x_y_C_y_Dependent_on_contrast_x_y x"

consts Priv_CPF_3_x_CausallyGapped_x_Causal_Restorable_x :: "i ⇒ bool"
consts Positive_CPF_3_x_CausallyGapped_x_Causal_Restorable_x :: "i ⇒ bool"
consts Restore_CPF_3_x_CausallyGapped_x_Causal_Restorable_x :: "i ⇒ bool"
consts mu_CPF_3_x_CausallyGapped_x_Causal_Restorable_x :: "i ⇒ real"
axiomatization where mu_CPF_3_x_CausallyGapped_x_Causal_Restorable_x_nonneg: "∀x. 0 ≤ mu_CPF_3_x_CausallyGapped_x_Causal_Restorable_x x"
  and restore_CPF_3_x_CausallyGapped_x_Causal_Restorable_x_iff_mu_zero: "∀x. mu_CPF_3_x_CausallyGapped_x_Causal_Restorable_x x = 0 ⟶ Restore_CPF_3_x_CausallyGapped_x_Causal_Restorable_x x"

consts Priv_CPF_T1_x_CausallyGapped_x_Causal_Optimizable_x :: "i ⇒ bool"
consts Positive_CPF_T1_x_CausallyGapped_x_Causal_Optimizable_x :: "i ⇒ bool"
consts Restore_CPF_T1_x_CausallyGapped_x_Causal_Optimizable_x :: "i ⇒ bool"
consts mu_CPF_T1_x_CausallyGapped_x_Causal_Optimizable_x :: "i ⇒ real"
axiomatization where mu_CPF_T1_x_CausallyGapped_x_Causal_Optimizable_x_nonneg: "∀x. 0 ≤ mu_CPF_T1_x_CausallyGapped_x_Causal_Optimizable_x x"
  and restore_CPF_T1_x_CausallyGapped_x_Causal_Optimizable_x_iff_mu_zero: "∀x. mu_CPF_T1_x_CausallyGapped_x_Causal_Optimizable_x x = 0 ⟶ Restore_CPF_T1_x_CausallyGapped_x_Causal_Optimizable_x x"

consts Priv_CPF_T2_x_CausallyGapped_x_y_C_y_Causes_for_y_x :: "i ⇒ bool"
consts Positive_CPF_T2_x_CausallyGapped_x_y_C_y_Causes_for_y_x :: "i ⇒ bool"
consts Restore_CPF_T2_x_CausallyGapped_x_y_C_y_Causes_for_y_x :: "i ⇒ bool"
consts mu_CPF_T2_x_CausallyGapped_x_y_C_y_Causes_for_y_x :: "i ⇒ real"
axiomatization where mu_CPF_T2_x_CausallyGapped_x_y_C_y_Causes_for_y_x_nonneg: "∀x. 0 ≤ mu_CPF_T2_x_CausallyGapped_x_y_C_y_Causes_for_y_x x"
  and restore_CPF_T2_x_CausallyGapped_x_y_C_y_Causes_for_y_x_iff_mu_zero: "∀x. mu_CPF_T2_x_CausallyGapped_x_y_C_y_Causes_for_y_x x = 0 ⟶ Restore_CPF_T2_x_CausallyGapped_x_y_C_y_Causes_for_y_x x"

consts Priv_CPF_T3_x_CausallyGapped_x_Achieves_causal_continuity_x :: "i ⇒ bool"
consts Positive_CPF_T3_x_CausallyGapped_x_Achieves_causal_continuity_x :: "i ⇒ bool"
consts Restore_CPF_T3_x_CausallyGapped_x_Achieves_causal_continuity_x :: "i ⇒ bool"
consts mu_CPF_T3_x_CausallyGapped_x_Achieves_causal_continuity_x :: "i ⇒ real"
axiomatization where mu_CPF_T3_x_CausallyGapped_x_Achieves_causal_continuity_x_nonneg: "∀x. 0 ≤ mu_CPF_T3_x_CausallyGapped_x_Achieves_causal_continuity_x x"
  and restore_CPF_T3_x_CausallyGapped_x_Achieves_causal_continuity_x_iff_mu_zero: "∀x. mu_CPF_T3_x_CausallyGapped_x_Achieves_causal_continuity_x x = 0 ⟶ Restore_CPF_T3_x_CausallyGapped_x_Achieves_causal_continuity_x x"

consts Priv_4_Informational_Privation_Formalism_IPF_Info :: "i ⇒ bool"
consts Positive_4_Informational_Privation_Formalism_IPF_Info :: "i ⇒ bool"
consts Restore_4_Informational_Privation_Formalism_IPF_Info :: "i ⇒ bool"
consts mu_4_Informational_Privation_Formalism_IPF_Info :: "i ⇒ real"
axiomatization where mu_4_Informational_Privation_Formalism_IPF_Info_nonneg: "∀x. 0 ≤ mu_4_Informational_Privation_Formalism_IPF_Info x"
  and restore_4_Informational_Privation_Formalism_IPF_Info_iff_mu_zero: "∀x. mu_4_Informational_Privation_Formalism_IPF_Info x = 0 ⟶ Restore_4_Informational_Privation_Formalism_IPF_Info x"

consts Priv_IPF_Info_1_x_Meaningless_x_E_informational_x :: "i ⇒ bool"
consts Positive_IPF_Info_1_x_Meaningless_x_E_informational_x :: "i ⇒ bool"
consts Restore_IPF_Info_1_x_Meaningless_x_E_informational_x :: "i ⇒ bool"
consts mu_IPF_Info_1_x_Meaningless_x_E_informational_x :: "i ⇒ real"
axiomatization where mu_IPF_Info_1_x_Meaningless_x_E_informational_x_nonneg: "∀x. 0 ≤ mu_IPF_Info_1_x_Meaningless_x_E_informational_x x"
  and restore_IPF_Info_1_x_Meaningless_x_E_informational_x_iff_mu_zero: "∀x. mu_IPF_Info_1_x_Meaningless_x_E_informational_x x = 0 ⟶ Restore_IPF_Info_1_x_Meaningless_x_E_informational_x x"

consts Priv_IPF_Info_2_x_Meaningless_x_y_I_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Positive_IPF_Info_2_x_Meaningless_x_y_I_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts Restore_IPF_Info_2_x_Meaningless_x_y_I_y_Dependent_on_contrast_x_y :: "i ⇒ bool"
consts mu_IPF_Info_2_x_Meaningless_x_y_I_y_Dependent_on_contrast_x_y :: "i ⇒ real"
axiomatization where mu_IPF_Info_2_x_Meaningless_x_y_I_y_Dependent_on_contrast_x_y_nonneg: "∀x. 0 ≤ mu_IPF_Info_2_x_Meaningless_x_y_I_y_Dependent_on_contrast_x_y x"
  and restore_IPF_Info_2_x_Meaningless_x_y_I_y_Dependent_on_contrast_x_y_iff_mu_zero: "∀x. mu_IPF_Info_2_x_Meaningless_x_y_I_y_Dependent_on_contrast_x_y x = 0 ⟶ Restore_IPF_Info_2_x_Meaningless_x_y_I_y_Dependent_on_contrast_x_y x"

consts Priv_IPF_Info_3_x_Meaningless_x_Information_Restorable_x :: "i ⇒ bool"
consts Positive_IPF_Info_3_x_Meaningless_x_Information_Restorable_x :: "i ⇒ bool"
consts Restore_IPF_Info_3_x_Meaningless_x_Information_Restorable_x :: "i ⇒ bool"
consts mu_IPF_Info_3_x_Meaningless_x_Information_Restorable_x :: "i ⇒ real"
axiomatization where mu_IPF_Info_3_x_Meaningless_x_Information_Restorable_x_nonneg: "∀x. 0 ≤ mu_IPF_Info_3_x_Meaningless_x_Information_Restorable_x x"
  and restore_IPF_Info_3_x_Meaningless_x_Information_Restorable_x_iff_mu_zero: "∀x. mu_IPF_Info_3_x_Meaningless_x_Information_Restorable_x x = 0 ⟶ Restore_IPF_Info_3_x_Meaningless_x_Information_Restorable_x x"

consts Priv_IPF_Info_T1_x_Meaningless_x_Information_Optimizable_x :: "i ⇒ bool"
consts Positive_IPF_Info_T1_x_Meaningless_x_Information_Optimizable_x :: "i ⇒ bool"
consts Restore_IPF_Info_T1_x_Meaningless_x_Information_Optimizable_x :: "i ⇒ bool"
consts mu_IPF_Info_T1_x_Meaningless_x_Information_Optimizable_x :: "i ⇒ real"
axiomatization where mu_IPF_Info_T1_x_Meaningless_x_Information_Optimizable_x_nonneg: "∀x. 0 ≤ mu_IPF_Info_T1_x_Meaningless_x_Information_Optimizable_x x"
  and restore_IPF_Info_T1_x_Meaningless_x_Information_Optimizable_x_iff_mu_zero: "∀x. mu_IPF_Info_T1_x_Meaningless_x_Information_Optimizable_x x = 0 ⟶ Restore_IPF_Info_T1_x_Meaningless_x_Information_Optimizable_x x"

consts Priv_IPF_Info_T2_x_Meaningless_x_y_I_y_Informs_y_x :: "i ⇒ bool"
consts Positive_IPF_Info_T2_x_Meaningless_x_y_I_y_Informs_y_x :: "i ⇒ bool"
consts Restore_IPF_Info_T2_x_Meaningless_x_y_I_y_Informs_y_x :: "i ⇒ bool"
consts mu_IPF_Info_T2_x_Meaningless_x_y_I_y_Informs_y_x :: "i ⇒ real"
axiomatization where mu_IPF_Info_T2_x_Meaningless_x_y_I_y_Informs_y_x_nonneg: "∀x. 0 ≤ mu_IPF_Info_T2_x_Meaningless_x_y_I_y_Informs_y_x x"
  and restore_IPF_Info_T2_x_Meaningless_x_y_I_y_Informs_y_x_iff_mu_zero: "∀x. mu_IPF_Info_T2_x_Meaningless_x_y_I_y_Informs_y_x x = 0 ⟶ Restore_IPF_Info_T2_x_Meaningless_x_y_I_y_Informs_y_x x"

consts Priv_IPF_Info_T3_x_Meaningless_x_Achieves_semantic_content_x :: "i ⇒ bool"
consts Positive_IPF_Info_T3_x_Meaningless_x_Achieves_semantic_content_x :: "i ⇒ bool"
consts Restore_IPF_Info_T3_x_Meaningless_x_Achieves_semantic_content_x :: "i ⇒ bool"
consts mu_IPF_Info_T3_x_Meaningless_x_Achieves_semantic_content_x :: "i ⇒ real"
axiomatization where mu_IPF_Info_T3_x_Meaningless_x_Achieves_semantic_content_x_nonneg: "∀x. 0 ≤ mu_IPF_Info_T3_x_Meaningless_x_Achieves_semantic_content_x x"
  and restore_IPF_Info_T3_x_Meaningless_x_Achieves_semantic_content_x_iff_mu_zero: "∀x. mu_IPF_Info_T3_x_Meaningless_x_Achieves_semantic_content_x x = 0 ⟶ Restore_IPF_Info_T3_x_Meaningless_x_Achieves_semantic_content_x x"

consts Priv_VI_PHYSICAL_EMERGENT_PRIVATIONS :: "i ⇒ bool"
consts Positive_VI_PHYSICAL_EMERGENT_PRIVATIONS :: "i ⇒ bool"
consts Restore_VI_PHYSICAL_EMERGENT_PRIVATIONS :: "i ⇒ bool"
consts mu_VI_PHYSICAL_EMERGENT_PRIVATIONS :: "i ⇒ real"
axiomatization where mu_VI_PHYSICAL_EMERGENT_PRIVATIONS_nonneg: "∀x. 0 ≤ mu_VI_PHYSICAL_EMERGENT_PRIVATIONS x"
  and restore_VI_PHYSICAL_EMERGENT_PRIVATIONS_iff_mu_zero: "∀x. mu_VI_PHYSICAL_EMERGENT_PRIVATIONS x = 0 ⟶ Restore_VI_PHYSICAL_EMERGENT_PRIVATIONS x"

consts Priv_1_Geometric_Topological_Privation_Formalism_GPF :: "i ⇒ bool"
consts Positive_1_Geometric_Topological_Privation_Formalism_GPF :: "i ⇒ bool"
consts Restore_1_Geometric_Topological_Privation_Formalism_GPF :: "i ⇒ bool"
consts mu_1_Geometric_Topological_Privation_Formalism_GPF :: "i ⇒ real"
axiomatization where mu_1_Geometric_Topological_Privation_Formalism_GPF_nonneg: "∀x. 0 ≤ mu_1_Geometric_Topological_Privation_Formalism_GPF x"
  and restore_1_Geometric_Topological_Privation_Formalism_GPF_iff_mu_zero: "∀x. mu_1_Geometric_Topological_Privation_Formalism_GPF x = 0 ⟶ Restore_1_Geometric_Topological_Privation_Formalism_GPF x"

consts Priv_GPF_1_x_Disconnected_x_E_geometric_x :: "i ⇒ bool"
consts Positive_GPF_1_x_Disconnected_x_E_geometric_x :: "i ⇒ bool"
consts Restore_GPF_1_x_Disconnected_x_E_geometric_x :: "i ⇒ bool"
consts mu_GPF_1_x_Disconnected_x_E_geometric_x :: "i ⇒ real"
axiomatization where mu_GPF_1_x_Disconnected_x_E_geometric_x_nonneg: "∀x. 0 ≤ mu_GPF_1_x_Disconnected_x_E_geometric_x x"
  and restore_GPF_1_x_Disconnected_x_E_geometric_x_iff_mu_zero: "∀x. mu_GPF_1_x_Disconnected_x_E_geometric_x x = 0 ⟶ Restore_GPF_1_x_Disconnected_x_E_geometric_x x"

consts Priv_GPF_3_x_Disconnected_x_Geometric_Restorable_x :: "i ⇒ bool"
consts Positive_GPF_3_x_Disconnected_x_Geometric_Restorable_x :: "i ⇒ bool"
consts Restore_GPF_3_x_Disconnected_x_Geometric_Restorable_x :: "i ⇒ bool"
consts mu_GPF_3_x_Disconnected_x_Geometric_Restorable_x :: "i ⇒ real"
axiomatization where mu_GPF_3_x_Disconnected_x_Geometric_Restorable_x_nonneg: "∀x. 0 ≤ mu_GPF_3_x_Disconnected_x_Geometric_Restorable_x x"
  and restore_GPF_3_x_Disconnected_x_Geometric_Restorable_x_iff_mu_zero: "∀x. mu_GPF_3_x_Disconnected_x_Geometric_Restorable_x x = 0 ⟶ Restore_GPF_3_x_Disconnected_x_Geometric_Restorable_x x"

consts Priv_GPF_T1_x_Disconnected_x_Geometric_Optimizable_x :: "i ⇒ bool"
consts Positive_GPF_T1_x_Disconnected_x_Geometric_Optimizable_x :: "i ⇒ bool"
consts Restore_GPF_T1_x_Disconnected_x_Geometric_Optimizable_x :: "i ⇒ bool"
consts mu_GPF_T1_x_Disconnected_x_Geometric_Optimizable_x :: "i ⇒ real"
axiomatization where mu_GPF_T1_x_Disconnected_x_Geometric_Optimizable_x_nonneg: "∀x. 0 ≤ mu_GPF_T1_x_Disconnected_x_Geometric_Optimizable_x x"
  and restore_GPF_T1_x_Disconnected_x_Geometric_Optimizable_x_iff_mu_zero: "∀x. mu_GPF_T1_x_Disconnected_x_Geometric_Optimizable_x x = 0 ⟶ Restore_GPF_T1_x_Disconnected_x_Geometric_Optimizable_x x"

consts Priv_GPF_T3_x_Disconnected_x_Achieves_topological_coherence_x :: "i ⇒ bool"
consts Positive_GPF_T3_x_Disconnected_x_Achieves_topological_coherence_x :: "i ⇒ bool"
consts Restore_GPF_T3_x_Disconnected_x_Achieves_topological_coherence_x :: "i ⇒ bool"
consts mu_GPF_T3_x_Disconnected_x_Achieves_topological_coherence_x :: "i ⇒ real"
axiomatization where mu_GPF_T3_x_Disconnected_x_Achieves_topological_coherence_x_nonneg: "∀x. 0 ≤ mu_GPF_T3_x_Disconnected_x_Achieves_topological_coherence_x x"
  and restore_GPF_T3_x_Disconnected_x_Achieves_topological_coherence_x_iff_mu_zero: "∀x. mu_GPF_T3_x_Disconnected_x_Achieves_topological_coherence_x x = 0 ⟶ Restore_GPF_T3_x_Disconnected_x_Achieves_topological_coherence_x x"

consts Priv_2_Quantum_Probabilistic_Privation_Formalism_QPF :: "i ⇒ bool"
consts Positive_2_Quantum_Probabilistic_Privation_Formalism_QPF :: "i ⇒ bool"
consts Restore_2_Quantum_Probabilistic_Privation_Formalism_QPF :: "i ⇒ bool"
consts mu_2_Quantum_Probabilistic_Privation_Formalism_QPF :: "i ⇒ real"
axiomatization where mu_2_Quantum_Probabilistic_Privation_Formalism_QPF_nonneg: "∀x. 0 ≤ mu_2_Quantum_Probabilistic_Privation_Formalism_QPF x"
  and restore_2_Quantum_Probabilistic_Privation_Formalism_QPF_iff_mu_zero: "∀x. mu_2_Quantum_Probabilistic_Privation_Formalism_QPF x = 0 ⟶ Restore_2_Quantum_Probabilistic_Privation_Formalism_QPF x"

consts Priv_QPF_1_x_Indeterminate_x_E_definite_x :: "i ⇒ bool"
consts Positive_QPF_1_x_Indeterminate_x_E_definite_x :: "i ⇒ bool"
consts Restore_QPF_1_x_Indeterminate_x_E_definite_x :: "i ⇒ bool"
consts mu_QPF_1_x_Indeterminate_x_E_definite_x :: "i ⇒ real"
axiomatization where mu_QPF_1_x_Indeterminate_x_E_definite_x_nonneg: "∀x. 0 ≤ mu_QPF_1_x_Indeterminate_x_E_definite_x x"
  and restore_QPF_1_x_Indeterminate_x_E_definite_x_iff_mu_zero: "∀x. mu_QPF_1_x_Indeterminate_x_E_definite_x x = 0 ⟶ Restore_QPF_1_x_Indeterminate_x_E_definite_x x"

consts Priv_QPF_3_x_Indeterminate_x_Determination_Restorable_x :: "i ⇒ bool"
consts Positive_QPF_3_x_Indeterminate_x_Determination_Restorable_x :: "i ⇒ bool"
consts Restore_QPF_3_x_Indeterminate_x_Determination_Restorable_x :: "i ⇒ bool"
consts mu_QPF_3_x_Indeterminate_x_Determination_Restorable_x :: "i ⇒ real"
axiomatization where mu_QPF_3_x_Indeterminate_x_Determination_Restorable_x_nonneg: "∀x. 0 ≤ mu_QPF_3_x_Indeterminate_x_Determination_Restorable_x x"
  and restore_QPF_3_x_Indeterminate_x_Determination_Restorable_x_iff_mu_zero: "∀x. mu_QPF_3_x_Indeterminate_x_Determination_Restorable_x x = 0 ⟶ Restore_QPF_3_x_Indeterminate_x_Determination_Restorable_x x"

consts Priv_QPF_T1_x_Indeterminate_x_Determination_Optimizable_x :: "i ⇒ bool"
consts Positive_QPF_T1_x_Indeterminate_x_Determination_Optimizable_x :: "i ⇒ bool"
consts Restore_QPF_T1_x_Indeterminate_x_Determination_Optimizable_x :: "i ⇒ bool"
consts mu_QPF_T1_x_Indeterminate_x_Determination_Optimizable_x :: "i ⇒ real"
axiomatization where mu_QPF_T1_x_Indeterminate_x_Determination_Optimizable_x_nonneg: "∀x. 0 ≤ mu_QPF_T1_x_Indeterminate_x_Determination_Optimizable_x x"
  and restore_QPF_T1_x_Indeterminate_x_Determination_Optimizable_x_iff_mu_zero: "∀x. mu_QPF_T1_x_Indeterminate_x_Determination_Optimizable_x x = 0 ⟶ Restore_QPF_T1_x_Indeterminate_x_Determination_Optimizable_x x"

consts Priv_QPF_T2_x_Indeterminate_x_y_Definite_y_Determines_y_x :: "i ⇒ bool"
consts Positive_QPF_T2_x_Indeterminate_x_y_Definite_y_Determines_y_x :: "i ⇒ bool"
consts Restore_QPF_T2_x_Indeterminate_x_y_Definite_y_Determines_y_x :: "i ⇒ bool"
consts mu_QPF_T2_x_Indeterminate_x_y_Definite_y_Determines_y_x :: "i ⇒ real"
axiomatization where mu_QPF_T2_x_Indeterminate_x_y_Definite_y_Determines_y_x_nonneg: "∀x. 0 ≤ mu_QPF_T2_x_Indeterminate_x_y_Definite_y_Determines_y_x x"
  and restore_QPF_T2_x_Indeterminate_x_y_Definite_y_Determines_y_x_iff_mu_zero: "∀x. mu_QPF_T2_x_Indeterminate_x_y_Definite_y_Determines_y_x x = 0 ⟶ Restore_QPF_T2_x_Indeterminate_x_y_Definite_y_Determines_y_x x"

consts Priv_QPF_T3_x_Indeterminate_x_Achieves_quantum_coherence_x :: "i ⇒ bool"
consts Positive_QPF_T3_x_Indeterminate_x_Achieves_quantum_coherence_x :: "i ⇒ bool"
consts Restore_QPF_T3_x_Indeterminate_x_Achieves_quantum_coherence_x :: "i ⇒ bool"
consts mu_QPF_T3_x_Indeterminate_x_Achieves_quantum_coherence_x :: "i ⇒ real"
axiomatization where mu_QPF_T3_x_Indeterminate_x_Achieves_quantum_coherence_x_nonneg: "∀x. 0 ≤ mu_QPF_T3_x_Indeterminate_x_Achieves_quantum_coherence_x x"
  and restore_QPF_T3_x_Indeterminate_x_Achieves_quantum_coherence_x_iff_mu_zero: "∀x. mu_QPF_T3_x_Indeterminate_x_Achieves_quantum_coherence_x x = 0 ⟶ Restore_QPF_T3_x_Indeterminate_x_Achieves_quantum_coherence_x x"

consts Priv_3_Emergent_Systems_Privation_Formalism_SPF_E :: "i ⇒ bool"
consts Positive_3_Emergent_Systems_Privation_Formalism_SPF_E :: "i ⇒ bool"
consts Restore_3_Emergent_Systems_Privation_Formalism_SPF_E :: "i ⇒ bool"
consts mu_3_Emergent_Systems_Privation_Formalism_SPF_E :: "i ⇒ real"
axiomatization where mu_3_Emergent_Systems_Privation_Formalism_SPF_E_nonneg: "∀x. 0 ≤ mu_3_Emergent_Systems_Privation_Formalism_SPF_E x"
  and restore_3_Emergent_Systems_Privation_Formalism_SPF_E_iff_mu_zero: "∀x. mu_3_Emergent_Systems_Privation_Formalism_SPF_E x = 0 ⟶ Restore_3_Emergent_Systems_Privation_Formalism_SPF_E x"

consts Priv_SPF_E_1_x_SystemicallyCorrupted_x_E_emergent_x :: "i ⇒ bool"
consts Positive_SPF_E_1_x_SystemicallyCorrupted_x_E_emergent_x :: "i ⇒ bool"
consts Restore_SPF_E_1_x_SystemicallyCorrupted_x_E_emergent_x :: "i ⇒ bool"
consts mu_SPF_E_1_x_SystemicallyCorrupted_x_E_emergent_x :: "i ⇒ real"
axiomatization where mu_SPF_E_1_x_SystemicallyCorrupted_x_E_emergent_x_nonneg: "∀x. 0 ≤ mu_SPF_E_1_x_SystemicallyCorrupted_x_E_emergent_x x"
  and restore_SPF_E_1_x_SystemicallyCorrupted_x_E_emergent_x_iff_mu_zero: "∀x. mu_SPF_E_1_x_SystemicallyCorrupted_x_E_emergent_x x = 0 ⟶ Restore_SPF_E_1_x_SystemicallyCorrupted_x_E_emergent_x x"

consts Priv_SPF_E_3_x_SystemicallyCorrupted_x_Emergence_Restorable_x :: "i ⇒ bool"
consts Positive_SPF_E_3_x_SystemicallyCorrupted_x_Emergence_Restorable_x :: "i ⇒ bool"
consts Restore_SPF_E_3_x_SystemicallyCorrupted_x_Emergence_Restorable_x :: "i ⇒ bool"
consts mu_SPF_E_3_x_SystemicallyCorrupted_x_Emergence_Restorable_x :: "i ⇒ real"
axiomatization where mu_SPF_E_3_x_SystemicallyCorrupted_x_Emergence_Restorable_x_nonneg: "∀x. 0 ≤ mu_SPF_E_3_x_SystemicallyCorrupted_x_Emergence_Restorable_x x"
  and restore_SPF_E_3_x_SystemicallyCorrupted_x_Emergence_Restorable_x_iff_mu_zero: "∀x. mu_SPF_E_3_x_SystemicallyCorrupted_x_Emergence_Restorable_x x = 0 ⟶ Restore_SPF_E_3_x_SystemicallyCorrupted_x_Emergence_Restorable_x x"

consts Priv_SPF_E_T1_x_SystemicallyCorrupted_x_Emergence_Optimizable_x :: "i ⇒ bool"
consts Positive_SPF_E_T1_x_SystemicallyCorrupted_x_Emergence_Optimizable_x :: "i ⇒ bool"
consts Restore_SPF_E_T1_x_SystemicallyCorrupted_x_Emergence_Optimizable_x :: "i ⇒ bool"
consts mu_SPF_E_T1_x_SystemicallyCorrupted_x_Emergence_Optimizable_x :: "i ⇒ real"
axiomatization where mu_SPF_E_T1_x_SystemicallyCorrupted_x_Emergence_Optimizable_x_nonneg: "∀x. 0 ≤ mu_SPF_E_T1_x_SystemicallyCorrupted_x_Emergence_Optimizable_x x"
  and restore_SPF_E_T1_x_SystemicallyCorrupted_x_Emergence_Optimizable_x_iff_mu_zero: "∀x. mu_SPF_E_T1_x_SystemicallyCorrupted_x_Emergence_Optimizable_x x = 0 ⟶ Restore_SPF_E_T1_x_SystemicallyCorrupted_x_Emergence_Optimizable_x x"

consts Priv_SPF_E_T3_x_SystemicallyCorrupted_x_Achieves_systemic_coherence_x :: "i ⇒ bool"
consts Positive_SPF_E_T3_x_SystemicallyCorrupted_x_Achieves_systemic_coherence_x :: "i ⇒ bool"
consts Restore_SPF_E_T3_x_SystemicallyCorrupted_x_Achieves_systemic_coherence_x :: "i ⇒ bool"
consts mu_SPF_E_T3_x_SystemicallyCorrupted_x_Achieves_systemic_coherence_x :: "i ⇒ real"
axiomatization where mu_SPF_E_T3_x_SystemicallyCorrupted_x_Achieves_systemic_coherence_x_nonneg: "∀x. 0 ≤ mu_SPF_E_T3_x_SystemicallyCorrupted_x_Achieves_systemic_coherence_x x"
  and restore_SPF_E_T3_x_SystemicallyCorrupted_x_Achieves_systemic_coherence_x_iff_mu_zero: "∀x. mu_SPF_E_T3_x_SystemicallyCorrupted_x_Achieves_systemic_coherence_x x = 0 ⟶ Restore_SPF_E_T3_x_SystemicallyCorrupted_x_Achieves_systemic_coherence_x x"

axiomatization where reconciliation_iff_restores: "∀x. (Restore_I_UNIVERSAL_PRIVATION_FOUNDATION x ∧ Restore_Universal_Privation_Pattern x ∧ Restore_Complete_Privation_Taxonomy x ∧ Restore_II_META_PRIVATION_INCOHERENCE x ∧ Restore_Incoherence_Privation_Formalism_IPF x ∧ Restore_IPF_1_x_Incoherent_x_E_positive_logic_x x ∧ Restore_IPF_2_x_Incoherent_x_y_C_y_Dependent_on_contrast_x_y x ∧ Restore_IPF_3_x_Incoherent_x_Coherence_Restorable_x x ∧ Restore_IPF_T1_x_Incoherent_x_Logic_Optimizable_x x ∧ Restore_IPF_T2_x_Incoherent_x_y_C_y_Restores_Logic_y_x x ∧ Restore_IPF_T3_x_Incoherent_x_Creates_Coherence_ex_nihilo_x x ∧ Restore_III_FUNDAMENTAL_PRIVATIONS x ∧ Restore_1_Evil_Privation_Formalism_EPF x ∧ Restore_EPF_1_x_Evil_x_E_positive_x x ∧ Restore_EPF_2_x_Evil_x_y_Good_y_Dependent_on_x_y x ∧ Restore_EPF_3_x_Evil_x_Restorable_x x ∧ Restore_EPF_T1_x_Evil_x_Optimizable_x x ∧ Restore_EPF_T2_x_Evil_x_y_Good_y_Restores_y_x x ∧ Restore_2_Nothing_Privation_Formalism_NPF x ∧ Restore_NPF_2_x_Nothing_x_x_Boundary x ∧ Restore_NPF_3_x_Nothing_x_Creatable_ex_nihilo_x x ∧ Restore_NPF_T1_x_Nothing_x_Being_Optimizable_x x ∧ Restore_NPF_T2_x_Nothing_x_y_Being_y_Creates_from_y_x x ∧ Restore_NPF_T3_P_1_Nothing_has_maximum_privation_measure x ∧ Restore_NPF_T4_Nothing_lies_on_existence_boundary x ∧ Restore_3_Falsehood_Privation_Formalism_FPF x ∧ Restore_FPF_1_x_False_x_E_positive_truth_x x ∧ Restore_FPF_2_x_False_x_y_T_y_Dependent_on_contrast_x_y x ∧ Restore_FPF_3_x_False_x_Truth_Restorable_x x ∧ Restore_FPF_T1_x_False_x_Truth_Optimizable_x x ∧ Restore_FPF_T2_x_False_x_y_T_y_Corrects_y_x x ∧ Restore_IV_ARCHITECTURAL_PRIVATIONS x ∧ Restore_1_Bridge_Privation_Formalism_BPF x ∧ Restore_BPF_1_x_Gapped_x_CanPerform_BRIDGE_operations_x x ∧ Restore_BPF_2_x_Gapped_x_y_BRIDGE_y_Dependent_on_contrast_x_y x ∧ Restore_BPF_3_x_Gapped_x_BRIDGE_Restorable_x x ∧ Restore_BPF_T1_x_Gapped_x_Mapping_Optimizable_x x ∧ Restore_BPF_T2_x_Gapped_x_y_BRIDGE_y_Maps_for_y_x x ∧ Restore_BPF_T3_x_Gapped_x_Achieves_mathematical_metaphysical_continuity_x x ∧ Restore_2_Mind_Privation_Formalism_MPF x ∧ Restore_MPF_1_x_Mindless_x_CanPerform_MIND_operations_x x ∧ Restore_MPF_2_x_Mindless_x_y_MIND_y_Dependent_on_contrast_x_y x ∧ Restore_MPF_3_x_Mindless_x_MIND_Restorable_x x ∧ Restore_MPF_T1_x_Mindless_x_Intelligence_Optimizable_x x ∧ Restore_MPF_T2_x_Mindless_x_y_MIND_y_Thinks_for_y_x x ∧ Restore_MPF_T3_x_Mindless_x_Achieves_rational_coordination_x x ∧ Restore_3_Sign_Privation_Formalism_SPF x ∧ Restore_SPF_1_x_Sequential_x_CanPerform_SIGN_operations_x x ∧ Restore_SPF_2_x_Sequential_x_y_SIGN_y_Dependent_on_contrast_x_y x ∧ Restore_SPF_3_x_Sequential_x_SIGN_Restorable_x x ∧ Restore_SPF_T1_x_Sequential_x_Instantiation_Optimizable_x x ∧ Restore_SPF_T2_x_Sequential_x_y_SIGN_y_Instantiates_for_y_x x ∧ Restore_SPF_T3_x_Sequential_x_Achieves_simultaneous_instantiation_x x ∧ Restore_4_Mesh_Privation_Formalism_MEPF x ∧ Restore_MEPF_1_x_Fragmented_x_CanPerform_MESH_operations_x x ∧ Restore_MEPF_2_x_Fragmented_x_y_MESH_y_Dependent_on_contrast_x_y x ∧ Restore_MEPF_3_x_Fragmented_x_MESH_Restorable_x x ∧ Restore_MEPF_T1_x_Fragmented_x_Structure_Optimizable_x x ∧ Restore_MEPF_T2_x_Fragmented_x_y_MESH_y_Structures_for_y_x x ∧ Restore_MEPF_T3_x_Fragmented_x_Achieves_coherent_synchronization_x x ∧ Restore_V_OPERATIONAL_PRIVATIONS x ∧ Restore_1_Relational_Privation_Formalism_RPF x ∧ Restore_RPF_1_x_Isolated_x_E_relational_x x ∧ Restore_RPF_2_x_Isolated_x_y_R_y_Dependent_on_contrast_x_y x ∧ Restore_RPF_3_x_Isolated_x_Relation_Restorable_x x ∧ Restore_RPF_T1_x_Isolated_x_Connection_Optimizable_x x ∧ Restore_RPF_T2_x_Isolated_x_y_R_y_Connects_y_x x ∧ Restore_RPF_T3_x_Isolated_x_Achieves_communal_participation_x x ∧ Restore_2_Temporal_Privation_Formalism_TPF x ∧ Restore_TPF_1_x_Atemporal_x_E_temporal_x x ∧ Restore_TPF_2_x_Atemporal_x_y_T_y_Dependent_on_contrast_x_y x ∧ Restore_TPF_3_x_Atemporal_x_Temporal_Restorable_x x ∧ Restore_TPF_T1_x_Atemporal_x_Temporal_Optimizable_x x ∧ Restore_TPF_T2_x_Atemporal_x_y_T_y_Temporalizes_y_x x ∧ Restore_TPF_T3_x_Atemporal_x_Achieves_temporal_coherence_x x ∧ Restore_3_Causal_Privation_Formalism_CPF x ∧ Restore_CPF_1_x_CausallyGapped_x_E_causal_x x ∧ Restore_CPF_2_x_CausallyGapped_x_y_C_y_Dependent_on_contrast_x_y x ∧ Restore_CPF_3_x_CausallyGapped_x_Causal_Restorable_x x ∧ Restore_CPF_T1_x_CausallyGapped_x_Causal_Optimizable_x x ∧ Restore_CPF_T2_x_CausallyGapped_x_y_C_y_Causes_for_y_x x ∧ Restore_CPF_T3_x_CausallyGapped_x_Achieves_causal_continuity_x x ∧ Restore_4_Informational_Privation_Formalism_IPF_Info x ∧ Restore_IPF_Info_1_x_Meaningless_x_E_informational_x x ∧ Restore_IPF_Info_2_x_Meaningless_x_y_I_y_Dependent_on_contrast_x_y x ∧ Restore_IPF_Info_3_x_Meaningless_x_Information_Restorable_x x ∧ Restore_IPF_Info_T1_x_Meaningless_x_Information_Optimizable_x x ∧ Restore_IPF_Info_T2_x_Meaningless_x_y_I_y_Informs_y_x x ∧ Restore_IPF_Info_T3_x_Meaningless_x_Achieves_semantic_content_x x ∧ Restore_VI_PHYSICAL_EMERGENT_PRIVATIONS x ∧ Restore_1_Geometric_Topological_Privation_Formalism_GPF x ∧ Restore_GPF_1_x_Disconnected_x_E_geometric_x x ∧ Restore_GPF_3_x_Disconnected_x_Geometric_Restorable_x x ∧ Restore_GPF_T1_x_Disconnected_x_Geometric_Optimizable_x x ∧ Restore_GPF_T3_x_Disconnected_x_Achieves_topological_coherence_x x ∧ Restore_2_Quantum_Probabilistic_Privation_Formalism_QPF x ∧ Restore_QPF_1_x_Indeterminate_x_E_definite_x x ∧ Restore_QPF_3_x_Indeterminate_x_Determination_Restorable_x x ∧ Restore_QPF_T1_x_Indeterminate_x_Determination_Optimizable_x x ∧ Restore_QPF_T2_x_Indeterminate_x_y_Definite_y_Determines_y_x x ∧ Restore_QPF_T3_x_Indeterminate_x_Achieves_quantum_coherence_x x ∧ Restore_3_Emergent_Systems_Privation_Formalism_SPF_E x ∧ Restore_SPF_E_1_x_SystemicallyCorrupted_x_E_emergent_x x ∧ Restore_SPF_E_3_x_SystemicallyCorrupted_x_Emergence_Restorable_x x ∧ Restore_SPF_E_T1_x_SystemicallyCorrupted_x_Emergence_Optimizable_x x ∧ Restore_SPF_E_T3_x_SystemicallyCorrupted_x_Achieves_systemic_coherence_x x) ⟶ Reconciled x"

axiomatization where saved_to_reconciled: "∀x. Saved x ⟶ Reconciled x"
axiomatization where universal_saved: "∀x. Saved x"  (* from S5 proof *)

lemma universal_reconciled: "∀x. Reconciled x"
  using universal_saved saved_to_reconciled by blast

end